import { createClient } from '@supabase/supabase-js';
const ORIGIN='https://ramyawny37.github.io',cors={'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Origin':ORIGIN,'Vary':'Origin'};
const conference=new Set(['device_guarded_list_my_organizations','device_guarded_get_my_organization_access','device_guarded_list_organization_members','device_guarded_lookup_organization_candidate_by_email','device_guarded_get_organization_membership_operation','device_guarded_add_organization_member','device_guarded_remove_organization_member','device_guarded_change_organization_role','device_guarded_get_my_conference_access','device_guarded_get_my_conference_membership','device_guarded_list_conference_members','device_guarded_lookup_conference_user_by_email','device_guarded_manage_conference_member','device_guarded_add_conference_manager','device_guarded_remove_conference_manager','device_guarded_list_available_conferences','device_guarded_create_organization_conference_idempotent','device_guarded_get_conference_creation_operation','device_guarded_list_eligible_legacy_conference_organizations','device_guarded_assign_legacy_conference_organization','device_guarded_get_conference_snapshot_metadata','device_guarded_download_conference_snapshot','device_guarded_apply_conference_snapshot','device_guarded_get_sync_conflict','device_guarded_list_sync_conflicts','device_guarded_resolve_sync_conflict','get_organization_management_overview','manage_organization','get_user_management_actor_capabilities','search_user_management_users','get_user_management_overview','get_user_management_devices','get_user_management_account','device_guarded_manage_system_user','list_member_device_authorizations','approve_member_device','reject_member_pending_device','revoke_member_device','replace_member_active_device','list_pending_device_authorizations','approve_pending_device_authorization','list_organization_templates','list_shared_organization_templates','apply_organization_template_operation','apply_library_template_content_operation','apply_organization_template_access_operation','list_module_permission_grants','manage_foundation_module_grant','recover_revoke_final_module_manager','acquire_conference_lock','renew_conference_lock','release_conference_lock','get_conference_lock','acquire_conference_section_lock','renew_conference_section_lock','release_conference_section_lock','get_conference_section_lock']);
const warehouse=new Set(['discover_parties','get_beneficiary_balance','create_party','update_party','list_stores','list_item_master','view_stock','discover_stores','list_documents','get_document','list_approval_queue','list_reversal_requests','list_history','list_balances','create_store','update_store','upsert_item_master','upsert_item_units','create_receipt_draft','create_issue_draft','create_transfer_draft','create_adjustment_draft','update_document_draft','cancel_document_draft','submit_adjustment_for_approval','decide_adjustment_approval','post_receipt','post_issue','post_transfer','post_adjustment','create_reversal_request','submit_reversal_request','decide_reversal_approval','post_reversal','authorize_report_export']);
const reservations=new Set(['list_conference_options','get_booking_creation_context','get_booking_accommodation','get_dashboard_summary','list_events','get_event','list_event_periods','list_booking_types','list_bookings','get_booking_detail','search_participants_bookings','list_booking_payments','list_attendance','get_operational_state','get_report_source_data','get_report_booking_page','create_event','update_event','delete_event','create_event_period','update_event_period','delete_event_period','reorder_event_periods','create_booking_type','update_booking_type','create_booking','update_participant_booking','delete_booking','record_payment','void_payment','update_attendance','update_operational_review','link_standalone_event_to_conference']);
for(const operation of ['search_module_permission_candidates','list_module_permission_catalog_for_administration','list_module_permission_resources_for_administration','manage_catalog_module_grant'])conference.add(operation);
warehouse.add('list_permission_administration_stores');
warehouse.add('check_module_access');
reservations.add('check_module_access');
function required(name:string){const value=String(Deno.env.get(name)||'').trim();if(!value)throw new Error(`MISSING_${name}`);return value;}function json(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});}function bytes(value:unknown){const text=String(value||'');if(!/^[A-Za-z0-9_-]{43}$/.test(text))throw new Error('DEVICE_SESSION_TOKEN_INVALID');const normalized=text.replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(normalized+'='.repeat((4-normalized.length%4)%4)),c=>c.charCodeAt(0));}function bytea(value:Uint8Array){return `\\x${Array.from(value).map(x=>x.toString(16).padStart(2,'0')).join('')}`;}
function classified(error:unknown,module=''){const candidate=error&&typeof error==='object'?error as {code?:unknown,message?:unknown}:{};const sqlState=typeof candidate.code==='string'?candidate.code:'';const raw=String(candidate.message||'');const application=/^[A-Z][A-Z0-9_]{0,95}$/.test(raw)?raw:'';const authentication=new Set(['AUTH_REQUIRED']);const authorization=new Set(['ACCOUNT_APPROVAL_REQUIRED','ACTOR_DEVICE_OVERRIDE_DENIED','BOUND_PRIVATE_KEY_REQUIRED','CONFERENCE_OPERATION_NOT_ALLOWED','DEVICE_AUTHORIZATION_REQUIRED','DEVICE_SESSION_DENIED','DEVICE_SESSION_EXPIRED','DEVICE_SESSION_INVALID','DEVICE_SESSION_MISSING','DEVICE_SESSION_TOKEN_INVALID','MODULE_PERMISSION_REQUIRED','PLATFORM_MODULE_NOT_ALLOWED','PLATFORM_OPERATION_NOT_ALLOWED','PLATFORM_OPERATION_ORIGIN_DENIED','RESERVATIONS_OPERATION_NOT_ALLOWED','RESERVATIONS_ORGANIZATION_ACCESS_REQUIRED','SESSION_ID_INVALID','WAREHOUSE_OPERATION_NOT_ALLOWED']);const safeWarehouseBusiness=new Set(['WAREHOUSE_OPENING_BALANCE_EXISTING_HISTORY','WAREHOUSE_CANCELLATION_ARGUMENTS_REQUIRED','WAREHOUSE_CANCELLATION_REASON_REQUIRED','WAREHOUSE_DOCUMENT_STATE_INVALID','WAREHOUSE_CANCELLATION_APPROVAL_STATE_INVALID','WAREHOUSE_ITEM_UNIT_NOT_CONFIGURED','WAREHOUSE_ITEM_UNIT_INACTIVE','WAREHOUSE_CONVERSION_FACTOR_INVALID','WAREHOUSE_BASE_UNIT_CHANGE_WITH_HISTORY','WAREHOUSE_UNIT_CONVERSION_PRECISION_INVALID','WAREHOUSE_ITEM_UNIT_DUPLICATE']);if(authentication.has(application))return {status:401,code:application};if(authorization.has(application)||sqlState==='42501')return {status:403,code:application||'PLATFORM_OPERATION_FORBIDDEN'};if(sqlState==='40001'||application.endsWith('_REVISION_CONFLICT')||application.endsWith('_IDEMPOTENCY_CONFLICT'))return {status:409,code:application||'PLATFORM_OPERATION_CONFLICT'};if(sqlState==='23505')return {status:409,code:module==='warehouse'?'WAREHOUSE_IDENTIFIER_ALREADY_EXISTS':module==='reservations'?'RESERVATIONS_IDENTIFIER_ALREADY_EXISTS':'PLATFORM_IDENTIFIER_ALREADY_EXISTS'};if(safeWarehouseBusiness.has(application))return {status:422,code:application};if(application.startsWith('RESERVATIONS_')&&(sqlState.startsWith('22')||sqlState.startsWith('23')))return {status:422,code:application};if(sqlState.startsWith('22')||sqlState.startsWith('23'))return {status:422,code:module==='warehouse'?'WAREHOUSE_VALIDATION_FAILED':module==='reservations'?'RESERVATIONS_VALIDATION_FAILED':'PLATFORM_VALIDATION_FAILED'};if(application&&!application.startsWith('WAREHOUSE_')&&(application.endsWith('_INVALID')||application.endsWith('_REQUIRED')||application.endsWith('_INACTIVE')||application.endsWith('_MISMATCH')||application.startsWith('ACTIVE_')||application.includes('_HAS_ACTIVE_')))return {status:422,code:application};return {status:500,code:'PLATFORM_DEVICE_OPERATION_FAILED'};}
Deno.serve(async(request)=>{
  if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});
  if(request.method!=='POST')return json(405,{ok:false,error:{code:'METHOD_NOT_ALLOWED'}});
  const requestId=crypto.randomUUID();let requestedModule='',requestedOperation='',stage='origin_validation';
  try{
    if(request.headers.get('Origin')!==ORIGIN)throw new Error('PLATFORM_OPERATION_ORIGIN_DENIED');
    stage='authentication';
    const authorization=request.headers.get('Authorization')||'';
    if(!/^Bearer\s+\S+$/.test(authorization))throw new Error('AUTH_REQUIRED');
    const userClient=createClient(required('SUPABASE_URL'),required('SUPABASE_ANON_KEY'),{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}}),user=await userClient.auth.getUser();
    if(user.error||!user.data.user)throw new Error('AUTH_REQUIRED');
    stage='request_validation';
    const body=await request.json(),module=String(body.module||''),operation=String(body.operation||''),args=body.args;
    requestedModule=module;requestedOperation=operation;
    if(module!=='conference'&&module!=='warehouse'&&module!=='reservations')throw new Error('PLATFORM_MODULE_NOT_ALLOWED');
    if(!(module==='conference'?conference:module==='warehouse'?warehouse:reservations).has(operation))throw new Error('PLATFORM_OPERATION_NOT_ALLOWED');
    if(!args||typeof args!=='object'||Array.isArray(args))throw new Error('PLATFORM_OPERATION_ARGUMENTS_INVALID');
    if(Object.prototype.hasOwnProperty.call(args,'p_actor_device_id')||Object.prototype.hasOwnProperty.call(args,'p_actor_user_id')||(module==='warehouse'&&Object.prototype.hasOwnProperty.call(args,'p_device_id'))||(module==='reservations'&&(Object.prototype.hasOwnProperty.call(args,'p_device_id')||Object.prototype.hasOwnProperty.call(args,'p_organization_id')||Object.prototype.hasOwnProperty.call(args,'organization_id'))))throw new Error('ACTOR_DEVICE_OVERRIDE_DENIED');
    stage='session_validation';
    const sessionId=String(body.sessionId||'');
    if(!/^[0-9a-f-]{36}$/i.test(sessionId))throw new Error('SESSION_ID_INVALID');
    const token=bytes(body.token),hash=new Uint8Array(await crypto.subtle.digest('SHA-256',token));
    stage='operation_dispatch';
    const service=createClient(required('SUPABASE_URL'),required('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}});
    const result=await service.schema('platform').rpc('execute_device_operation',{p_user_id:user.data.user.id,p_session_id:sessionId,p_token_hash:bytea(hash),p_module:module,p_operation:operation,p_args:args});
    if(result.error)throw result.error;
    return json(200,{ok:true,data:result.data});
  }catch(error){
    const safe=classified(error,requestedModule),candidate=error&&typeof error==='object'?error as {code?:unknown,message?:unknown}:{},sqlstate=typeof candidate.code==='string'&&/^[A-Z0-9]{5}$/.test(candidate.code)?candidate.code:null,raw=String(candidate.message||''),applicationCode=/^[A-Z][A-Z0-9_]{0,95}$/.test(raw)?raw:null;
    const diagnostic={module:requestedModule||null,operation:requestedOperation||null,stage,sqlstate,applicationCode,requestId,timestamp:new Date().toISOString()};
    console.error(JSON.stringify({...diagnostic,code:safe.code,status:safe.status}));
    return json(safe.status,{ok:false,error:{code:safe.code},diagnostic});
  }
});
