import { createClient } from '@supabase/supabase-js';
const ORIGIN='https://ramyawny37.github.io';
const cors={'Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'};
const allowed=new Set([
  'create_canonical_conference','mutate_conference_core','get_conference_core','list_conference_participations','create_conference_participation','set_conference_participation_status','set_conference_participation_guardian','delete_conference_participation','get_conference_accommodation','create_accommodation_house','update_accommodation_house','delete_accommodation_house','create_accommodation_floor','update_accommodation_floor','delete_accommodation_floor','create_accommodation_room','update_accommodation_room','delete_accommodation_room','assign_conference_accommodation','move_conference_accommodation','remove_conference_accommodation',
  'device_guarded_list_my_organizations','device_guarded_get_my_organization_access','device_guarded_list_organization_members','device_guarded_lookup_organization_candidate_by_email','device_guarded_get_organization_membership_operation','device_guarded_add_organization_member','device_guarded_remove_organization_member','device_guarded_change_organization_role',
  'device_guarded_get_my_conference_access','device_guarded_get_my_conference_membership','device_guarded_list_conference_members','device_guarded_lookup_conference_user_by_email','device_guarded_manage_conference_member','device_guarded_add_conference_manager','device_guarded_remove_conference_manager','device_guarded_list_available_conferences',
  'device_guarded_create_organization_conference_idempotent','device_guarded_get_conference_creation_operation','device_guarded_list_eligible_legacy_conference_organizations','device_guarded_assign_legacy_conference_organization','device_guarded_get_conference_snapshot_metadata','device_guarded_download_conference_snapshot','device_guarded_apply_conference_snapshot','device_guarded_get_sync_conflict','device_guarded_list_sync_conflicts','device_guarded_resolve_sync_conflict',
  'get_organization_management_overview','manage_organization','get_user_management_actor_capabilities','search_user_management_users','get_user_management_overview','get_user_management_devices','get_user_management_account','device_guarded_manage_system_user',
  'list_member_device_authorizations','approve_member_device','reject_member_pending_device','revoke_member_device','replace_member_active_device','list_pending_device_authorizations','approve_pending_device_authorization','list_organization_templates','list_shared_organization_templates','apply_organization_template_operation','apply_library_template_content_operation','apply_organization_template_access_operation',
  'list_module_permission_grants','manage_foundation_module_grant','recover_revoke_final_module_manager',
  'acquire_conference_lock','renew_conference_lock','release_conference_lock','get_conference_lock','acquire_conference_section_lock','renew_conference_section_lock','release_conference_section_lock','get_conference_section_lock'
]);
allowed.add('create_conference_participation_with_person');
allowed.add('get_conference_restaurant');
allowed.add('mutate_conference_restaurant');
function required(name:string){const value=String(Deno.env.get(name)||'');if(!value)throw new Error(`MISSING_${name}`);return value;}
function response(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});}
function bytes(value:unknown){const text=String(value||'');if(!/^[A-Za-z0-9_-]{43}$/.test(text))throw new Error('DEVICE_SESSION_TOKEN_INVALID');const normalized=text.replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(normalized+'='.repeat((4-normalized.length%4)%4)),c=>c.charCodeAt(0));}
function bytea(value:Uint8Array){return `\\x${Array.from(value).map(x=>x.toString(16).padStart(2,'0')).join('')}`;}
Deno.serve(async request=>{if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(request.method!=='POST'||request.headers.get('Origin')!==ORIGIN)return response(403,{ok:false,error:{code:'ORIGIN_DENIED'}});try{const authorization=request.headers.get('Authorization')||'';if(!/^Bearer\s+\S+$/.test(authorization))throw new Error('AUTH_REQUIRED');const authClient=createClient(required('SUPABASE_URL'),required('SUPABASE_ANON_KEY'),{global:{headers:{Authorization:authorization}},auth:{persistSession:false}});const userResult=await authClient.auth.getUser();if(userResult.error||!userResult.data.user)throw new Error('AUTH_REQUIRED');const text=await request.text();if(text.length>8*1024*1024)throw new Error('PAYLOAD_TOO_LARGE');const body=JSON.parse(text),operation=String(body.operation||''),args=body.args;if(!allowed.has(operation))throw new Error('CONFERENCE_OPERATION_NOT_ALLOWED');if(!args||typeof args!=='object'||Array.isArray(args)||Object.hasOwn(args,'p_actor_device_id')||(Object.hasOwn(args,'p_device_id')&&operation!=='approve_pending_device_authorization'))throw new Error('CONFERENCE_OPERATION_ARGUMENTS_INVALID');const token=bytes(body.token);const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',token));const service=createClient(required('SUPABASE_URL'),required('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}});const result=await service.schema('platform').rpc('execute_conference_device_operation',{p_user_id:userResult.data.user.id,p_session_id:String(body.sessionId||''),p_token_hash:bytea(hash),p_operation:operation,p_args:args});if(result.error)throw result.error;return response(200,{ok:true,data:result.data});}catch(error){const message=String((error as {message?:unknown})?.message||'CONFERENCE_DEVICE_OPERATION_DENIED');const safe=/^[A-Z][A-Z0-9_]{1,95}$/.test(message)?message:'CONFERENCE_DEVICE_OPERATION_DENIED';console.error(JSON.stringify({code:safe,stage:'conference-device-operation',timestamp:new Date().toISOString()}));return response(safe==='AUTH_REQUIRED'?401:403,{ok:false,error:{code:safe}});}});
