'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const housesSource=fs.readFileSync('houses.js','utf8');
const scriptSource=fs.readFileSync('script.js','utf8');
function extract(source,start,end){const a=source.indexOf('function '+start+'('),b=source.indexOf('function '+end+'(',a);assert(a>=0&&b>a,start+' extraction failed');return source.slice(a,b);}
const FLOOR='839ba547-4e96-497e-8c05-0c9825372a93';
const template={id:'8dc329f8-1b08-4928-b5c6-fa1f8a878a12',accessibleOrganizationIds:['org-a','org-b'],floors:[{id:FLOOR,name:'First',rooms:[{id:'existing-template-room',number:'101',beds:2},{id:'6cc0428f-2959-4f38-bb18-8d2e4f1e95dd',number:'502',beds:3,extraBeds:1,notes:'Laptop'},{id:'7aefa42b-485a-4a23-97f5-c49c6e2b1bad',number:'201',beds:2,notes:'iPhone'}]}]};
const house={id:'conference-house',sourceTemplateId:template.id,floors:[{id:'conference-floor',sourceTemplateFloorId:FLOOR,name:'First',rooms:[{id:'conference-room',sourceTemplateRoomId:'existing-template-room',number:'101',beds:2,guests:[],children:[]}]}]};
let generated=0;
const h={appData:{houseTemplates:[template]},uid:()=>`conference-new-${++generated}`,String,Array,parseInt};
vm.createContext(h);vm.runInContext(extract(housesSource,'getHouseTemplateById','ensureSelectedHouseTemplate'),h);
const before=JSON.stringify({template,house});
let available=h.getAvailableTemplateRoomsForConferenceHouse(house);
assert.deepStrictEqual(Array.from(available,x=>x.number),['502','201']);
assert.deepStrictEqual(Array.from(available,x=>x.templateRoomId),['6cc0428f-2959-4f38-bb18-8d2e4f1e95dd','7aefa42b-485a-4a23-97f5-c49c6e2b1bad']);
assert(available.every(x=>x.conferenceFloorId==='conference-floor'));
assert.strictEqual(JSON.stringify({template,house}),before,'discovery must be read-only');
const container={innerHTML:''};let saves=0,logs=0,renders=0,permissionGateAllows=false;
const current={houses:[house],accommodationDisplayedRoomIds:['conference-room'],accommodationDisplayStateInitialized:true};
const ui={activeRoomsManager:{houseId:house.id},getCurrentConference:()=>current,getHouseById:()=>house,ge:id=>id==='active_rooms_container'?container:null,ensureAccommodationDisplayState:()=>({'conference-room':true}),getAvailableTemplateRoomsForConferenceHouse:h.getAvailableTemplateRoomsForConferenceHouse,addAvailableTemplateRoomToConferenceHouse:h.addAvailableTemplateRoomToConferenceHouse,esc:String,requireAccommodationMutation:()=>true,requireLocalOnlyAccommodationMutation:()=>true,deepClone:value=>JSON.parse(JSON.stringify(value)),prepareAccommodationDisplayedRoomIds:(conference,ids)=>({ok:true,ids:conference.accommodationDisplayedRoomIds.concat(ids)}),commitAccommodationDisplayChange:(conference,ids)=>{conference.accommodationDisplayedRoomIds=ids;},save:()=>{saves++;return true;},addActivityLog:()=>{logs++;},renderAccommodation:()=>{renders++;}};
ui.window=ui;
ui.ConferencePermissionShadowGate=(handler,action)=>{assert.strictEqual(handler,'addAvailableTemplateRoom');assert.strictEqual(action,null);return permissionGateAllows;};
vm.createContext(ui);vm.runInContext(extract(scriptSource,'renderActiveRoomsManager','toggleActiveRoom'),ui);
ui.renderActiveRoomsManager();assert(container.innerHTML.includes('502'));assert(container.innerHTML.includes('201'));
assert.strictEqual(saves,0,'render/discovery must not save conference');
assert.strictEqual(ui.addAvailableTemplateRoom('6cc0428f-2959-4f38-bb18-8d2e4f1e95dd'),false);
assert.strictEqual(saves,0);assert.strictEqual(logs,0);assert.strictEqual(renders,0);
permissionGateAllows=true;
assert.strictEqual(ui.addAvailableTemplateRoom('6cc0428f-2959-4f38-bb18-8d2e4f1e95dd'),true);
assert.strictEqual(saves,1);assert.strictEqual(logs,1);assert.strictEqual(renders,1);
assert.notStrictEqual(house.floors[0].rooms[1].id,'6cc0428f-2959-4f38-bb18-8d2e4f1e95dd');
assert.strictEqual(house.floors[0].rooms[1].sourceTemplateRoomId,'6cc0428f-2959-4f38-bb18-8d2e4f1e95dd');
available=ui.getAvailableTemplateRoomsForConferenceHouse(house);
assert.deepStrictEqual(Array.from(available,x=>x.number),['201']);
assert.strictEqual(template.floors[0].rooms.length,3,'explicit add must not mutate template');
console.log('available template room discovery: PASS');
