const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
const sql=read('supabase/migrations/20261003200000_canonical_conference_air_conditioning.sql'),integration=read('js/platform-integration.js'),core=read('core.js'),accounts=read('js/conference/accounts.js'),script=read('script.js'),edge=read('supabase/functions/conference-device-operation/index.ts')+read('supabase/functions/platform-device-operation/index.ts');

test('normalized hierarchy uses canonical Conference, Accommodation house and room identities',()=>{assert.match(sql,/conference_air_conditioning_defaults/);assert.match(sql,/house_id uuid primary key references public\.conference_accommodation_houses/);assert.match(sql,/room_id uuid primary key references public\.conference_accommodation_rooms/);assert.doesNotMatch(sql,/air_conditioning_(state|document) jsonb/i)});
test('canonical pricing contract has one vocabulary and excludes manual and day override state',()=>{for(const value of ['PER_PERSON','PER_ROOM','PER_UNIT','FIXED','INCLUDED','DAY','NIGHT','CONFERENCE','ACTUAL_OCCUPANCY'])assert.match(sql,new RegExp(value));assert.doesNotMatch(sql,/manual_total|day_overrides|pricing_mode[^\n]*MANUAL/i)});
test('mutable facts are revisioned and derived totals are not persisted',()=>{assert.equal((sql.match(/revision bigint not null default 1/g)||[]).length,3);assert.match(sql,/CONFERENCE_AIR_CONDITIONING_REVISION_CONFLICT/);assert.doesNotMatch(sql,/calculated_total|person_name|room_name|occupancy_count/)});
test('existing canonical ledger supplies replay and audit exactly once',()=>{assert.match(sql,/conference_participation_operations/);assert.match(sql,/air_conditioning_mutation/);assert.match(sql,/CONFERENCE_PARTICIPATION_OPERATION_MISMATCH/);assert.match(sql,/return prior\.result/);assert.doesNotMatch(sql,/air_conditioning_operations|air_conditioning_replay/);assert.match(sql,/conference\.air_conditioning\.configuration_changed/)});
test('exact Air Conditioning permissions and approved device boundary protect operations',()=>{assert.match(sql,/conference\.air_conditioning\.view/);assert.match(sql,/conference\.air_conditioning\.manage/);assert.match(sql,/APPROVED_DEVICE_SESSION_REQUIRED/);assert.doesNotMatch(sql,/conference\.accounts\.|conference_members|\bowner\b|\bmanager\b|\bviewer\b/);assert.match(edge,/get_conference_air_conditioning/);assert.match(edge,/mutate_conference_air_conditioning/)});
test('ACL and RLS deny direct browser/service access',()=>{assert.equal((sql.match(/force row level security/g)||[]).length,3);assert.match(sql,/revoke all on table[\s\S]*from public,anon,authenticated,service_role/);assert.match(sql,/revoke all on function[\s\S]*from public,anon,authenticated,service_role/)});
test('linked snapshot strips both superseded legacy authorities',()=>{assert.match(integration,/delete conference\.airConditioningV3/);assert.match(integration,/delete conference\.accounts\.settings\.airConditioningDefaults/);assert.match(integration,/delete conference\.accounts\.expenses\.airConditioning/)});
test('linked read and mutation use protected canonical operations and physically retire runtime legacy',async()=>{const calls=[],remote='10000000-0000-4000-8000-000000000001',response={conferenceId:remote,defaultConfiguration:{enabled:true,pricing_basis:'PER_ROOM',time_basis:'DAY',duration_basis:'CONFERENCE',unit_price:4,fixed_amount:null,include_empty_rooms:false,include_closed_rooms:false,units_count:null,revision:1},houseOverrides:[],roomOverrides:[]},conference={id:'local',airConditioningV3:{enabled:true},accounts:{settings:{airConditioningDefaults:{}},expenses:{airConditioning:{}}}};const c={window:null,console,Promise,JSON,Object,String,Array,Date,RegExp,Error,Uint8Array,Math,isFinite,navigator:{onLine:true},crypto:{randomUUID:()=> '20000000-0000-4000-8000-000000000001'},appData:{conferences:[conference]},ConferenceLinkStore:{get:()=>({linkStatus:'linked',remoteConferenceId:remote})},PlatformDeviceSession:{invokeModuleProtected(module,operation,args){calls.push({module,operation,args});return Promise.resolve(response)}},addEventListener(){},dispatchEvent(){},CustomEvent:function(){},document:{getElementById(){return null},addEventListener(){}}};c.window=c;vm.runInNewContext(integration,c);await c.PlatformIntegration.hydrateConferenceAirConditioning('local',remote);assert.equal('airConditioningV3' in conference,false);assert.equal('airConditioningDefaults' in conference.accounts.settings,false);assert.equal('airConditioning' in conference.accounts.expenses,false);await c.PlatformIntegration.mutateConferenceAirConditioning('local','CONFERENCE',null,'SET',{enabled:true});assert.deepEqual(calls.map(x=>x.operation),['get_conference_air_conditioning','mutate_conference_air_conditioning']);assert.equal(calls[1].args.p_expected_revision,1)});
test('linked calculation and Accounts consume one canonical projection',()=>{assert.match(integration,/function calculateConferenceAirConditioning/);assert.doesNotMatch(core,/function calculateCanonicalAirConditioningProjection/);assert.match(core,/integration\.calculateConferenceAirConditioning\(conference\.id\)/);assert.match(accounts,/return calculateAirConditioningSummary\(current\)/);assert.doesNotMatch(accounts,/canonical_air_conditioning/);assert.match(script,/mutateConferenceAirConditioning\(current\.id,'CONFERENCE'/)});
test('house and room operations preserve inheritance and subtree isolation',()=>{assert.match(sql,/p_scope not in\('CONFERENCE','HOUSE','ROOM'\)/);assert.match(sql,/CLEAR_SUBTREE/);assert.match(accounts,/mutateConferenceAirConditioning\(conference\.id,'HOUSE'/);assert.match(accounts,/mutateConferenceAirConditioning\(conference\.id,'ROOM'/)});
test('local-only legacy behavior remains behind absence of canonical state',()=>{assert.match(core,/conference\.airConditioningV3=normalizeAirConditioningV3/);assert.match(script,/if\(state\)[\s\S]*if\(window\.ConferencePermissionShadowGate/)});
