'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const test=require('node:test');
const root=path.join(__dirname,'..');
const migration=path.join(root,'supabase/migrations/20261007120000_canonical_accommodation_pricing_room_inclusion.sql');
const pricing=path.join(root,'supabase/migrations/20261003180000_canonical_conference_accommodation_pricing.sql');
const sql=fs.readFileSync(migration,'utf8');

test('C1A.3 persists exclusions only under the existing Accommodation Pricing owner',()=>{
  assert.match(sql,/create table public\.conference_accommodation_pricing_room_exclusions/);
  assert.match(sql,/primary key\(conference_id,room_id\)/);assert.match(sql,/references public\.conference_accommodation_rooms\(conference_id,id\)[\s\S]*on delete cascade/);
  assert.ok(sql.includes("''includedInPricing'',not exists"));assert.match(sql,/EXCLUDE_ROOM/);assert.match(sql,/REMOVE_ROOM_EXCLUSION/);
  assert.doesNotMatch(sql,/accommodationDisplayedRoomIds|displayedRoomIds|includedRoomIds|conference_snapshots|activityLog|saveAppData|\bsave\(/);
  assert.doesNotMatch(sql,/create table[^;]*(ledger|operation)|jsonb[^;]*(exclusion|room.inclusion)/i);
});

test('C1A.3 reuses pricing revision, operation, permission, replay, audit and ACL architecture',()=>{
  assert.match(sql,/create or replace function public\.mutate_conference_accommodation_pricing/);
  assert.match(sql,/'conference\.accommodation\.manage'/);assert.doesNotMatch(sql,/conference\.accounts\.manage|conference_members/);
  assert.match(sql,/accommodation_pricing_mutation/);assert.match(sql,/CONFERENCE_PARTICIPATION_OPERATION_MISMATCH/);assert.match(sql,/CONFERENCE_ACCOMMODATION_PRICING_REVISION_CONFLICT/);
  assert.match(sql,/revision=revision\+1/);assert.match(sql,/insert into platform\.audit_events/);assert.match(sql,/force row level security/);
});

const pgApp='/Applications/Postgres.app/Contents/Versions/latest/bin';
const pgBin=fs.existsSync(path.join(pgApp,'psql'))?pgApp:'';
const database=`conference_c1a3_${process.pid}_${Date.now()}`;
const connection=['-h',process.env.PGHOST||'/tmp','-p',process.env.PGPORT||'5432','-U',process.env.PGUSER||os.userInfo().username];
const env=Object.fromEntries(Object.entries(process.env).filter(([key])=>!key.startsWith('PG')&&!/(?:^DIRECT_URL$|(?:DATABASE|DB|POSTGRES|SUPABASE).*URL)/i.test(key)));
function command(name,args){return execFileSync(pgBin?path.join(pgBin,name):name,[...connection,...args],{encoding:'utf8',stdio:'pipe',env}).trim();}
function query(statement){return command('psql',['-X','-v','ON_ERROR_STOP=1','-At','-d',database,'-c',statement]);}
function rejects(statement,pattern){assert.throws(()=>query(statement),error=>pattern.test(String(error.stderr)),String(pattern));}

test('C1A.3 disposable PostgreSQL proves inclusion lifecycle, security, replay and rollback',()=>{
  const actor='10000000-0000-4000-8000-000000000001',denied='10000000-0000-4000-8000-000000000002',accounts='10000000-0000-4000-8000-000000000003';
  const device='20000000-0000-4000-8000-000000000001',wrong='20000000-0000-4000-8000-000000000002',revoked='20000000-0000-4000-8000-000000000003';
  const authz='30000000-0000-4000-8000-000000000001',conference='40000000-0000-4000-8000-000000000001',otherConference='40000000-0000-4000-8000-000000000002';
  const roomA='50000000-0000-4000-8000-000000000001',roomB='50000000-0000-4000-8000-000000000002',roomOther='50000000-0000-4000-8000-000000000003',roomNew='50000000-0000-4000-8000-000000000004';
  let sequence=0;const op=()=>`60000000-0000-4000-8000-${String(++sequence).padStart(12,'0')}`;
  const roles=['anon','authenticated','service_role'],created=[];
  const context=(user,actorDevice)=>`set local platform.phase1c_context='${JSON.stringify({purpose:'PLATFORM_DEVICE_SESSION_DISPATCH',user_id:user,device_id:actorDevice})}';`;
  const mutate=(user,actorDevice,operation,revision,action,room)=>`begin;${context(user,actorDevice)}select public.mutate_conference_accommodation_pricing('${actorDevice}','${operation}','${conference}',${revision},jsonb_build_object('action','${action}','roomId','${room}'));commit;`;
  const read=()=>`begin;${context(actor,device)}select public.get_conference_accommodation('${device}','${conference}');commit;`;
  try{command('psql',['-X','-At','-d','postgres','-c','select 1']);}catch{assert.fail('isolated/local PostgreSQL is required; do not silently skip');}
  command('createdb',[database]);
  try{
    for(const role of roles)if(query(`select exists(select 1 from pg_roles where rolname='${role}')`)==='f'){query(`create role ${role} nologin`);created.push(role);}
    query(`create extension pgcrypto;create schema platform;create schema platform_private;
      create table platform.profiles(user_id uuid primary key);create table platform.user_device_authorizations(id uuid primary key,user_id uuid,device_id uuid,status text);
      create table platform.audit_events(id uuid primary key default gen_random_uuid(),actor_user_id uuid,actor_device_authorization_id uuid,domain text,module text,action text,entity_type text,entity_id uuid,scope_type text,old_values jsonb,new_values jsonb,metadata jsonb,operation_id uuid,source text);
      create table public.conferences(id uuid primary key,status text,deleted_at timestamptz);
      create table public.conference_accommodation_houses(id uuid primary key,conference_id uuid);
      create table public.conference_accommodation_rooms(id uuid primary key,conference_id uuid not null,room_number text,is_closed boolean not null default false,revision bigint not null default 1,unique(conference_id,id));
      create table public.conference_participation_operations(actor_user_id uuid references platform.profiles(user_id),operation_id uuid,operation text constraint conference_participation_operations_operation_check check(operation in('create','create_with_person','set_status','set_guardian','delete','transport_vehicle_create','transport_vehicle_update','transport_vehicle_delete','transport_assignment_set','transport_assignment_remove','restaurant_mutation')),request jsonb,result jsonb,created_at timestamptz,primary key(actor_user_id,operation_id));
      create table public.test_access(user_id uuid primary key,accommodation_view boolean,accommodation_manage boolean,accounts_manage boolean,returned_actor uuid);
      create function platform_private.validated_phase1c_device_authorization(a uuid,d uuid) returns uuid language sql stable as $$select id from platform.user_device_authorizations where user_id=a and device_id=d and status='approved'$$;
      create function public.require_effective_module_permission(d uuid,m text,p text,s text,r text) returns jsonb language plpgsql stable as $$declare c jsonb;a uuid;x public.test_access%rowtype;begin c:=nullif(current_setting('platform.phase1c_context',true),'')::jsonb;a:=(c->>'user_id')::uuid;select * into x from public.test_access where user_id=a;if not found or (p='conference.accommodation.view' and not x.accommodation_view) or (p='conference.accommodation.manage' and not x.accommodation_manage) then raise exception 'MODULE_PERMISSION_REQUIRED' using errcode='42501';end if;return jsonb_build_object('actorUserId',coalesce(x.returned_actor,a),'authoritySource','module_grant','grantId','70000000-0000-4000-8000-000000000001');end$$;
      create function platform_private.require_conference_accommodation_context(d uuid,cid uuid,p text,mutation boolean) returns jsonb language plpgsql stable as $$declare x jsonb;a uuid;begin x:=public.require_effective_module_permission(d,'conference',p,'conference',cid::text);a:=(x->>'actorUserId')::uuid;if platform_private.validated_phase1c_device_authorization(a,d) is null then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;if not exists(select 1 from public.conferences where id=cid and deleted_at is null) then raise exception 'CONFERENCE_NOT_FOUND';end if;return x;end$$;
      create function platform_private.require_exact_jsonb_keys(p jsonb,required text[],optional text[] default '{}') returns void language plpgsql as $$declare actual text[];begin select coalesce(array_agg(key order by key),'{}') into actual from jsonb_object_keys(p) key;if actual<>coalesce((select array_agg(x order by x) from unnest(required||optional) x),'{}') then raise exception 'PLATFORM_OPERATION_ARGUMENT_INVALID' using errcode='22023';end if;end$$;
      create function public.get_conference_accommodation(p_device uuid,p_conference uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare result jsonb;begin perform platform_private.require_conference_accommodation_context(p_device,p_conference,'conference.accommodation.view',false);select coalesce(jsonb_agg(jsonb_build_object('roomId',r.id,'roomNumber',r.room_number,'isClosed',r.is_closed,'revision',r.revision,'occupancies','[]'::jsonb) order by r.id),'[]') into result from public.conference_accommodation_rooms r where r.conference_id=p_conference;return jsonb_build_object('conferenceId',p_conference,'houses',result);end$$;
      create function platform_private.route_canonical_conference_operation(a uuid,b uuid,c bytea,d uuid,p_operation text,p_args jsonb) returns jsonb language plpgsql as $$begin if p_operation='get_conference_restaurant' then return '{}'::jsonb;end if;return '{}'::jsonb;end$$;
      insert into platform.profiles values('${actor}'),('${denied}'),('${accounts}');insert into public.test_access values('${actor}',true,true,false,null),('${denied}',true,false,false,null),('${accounts}',true,false,true,null);
      insert into platform.user_device_authorizations values('${authz}','${actor}','${device}','approved'),(gen_random_uuid(),'${actor}','${wrong}','approved'),(gen_random_uuid(),'${actor}','${revoked}','revoked'),(gen_random_uuid(),'${denied}','${wrong}','approved'),(gen_random_uuid(),'${accounts}','${wrong}','approved');
      insert into public.conferences values('${conference}','active',null),('${otherConference}','active',null);insert into public.conference_accommodation_houses values(gen_random_uuid(),'${conference}');insert into public.conference_accommodation_rooms values('${roomA}','${conference}','101',false,1),('${roomB}','${conference}','102',false,1),('${roomOther}','${otherConference}','101',false,1);`);
    command('psql',['-X','-v','ON_ERROR_STOP=1','-d',database,'-f',pricing]);command('psql',['-X','-v','ON_ERROR_STOP=1','-d',database,'-f',migration]);
    assert.equal(query(`select count(*) from public.conference_accommodation_pricing_room_exclusions`),'0');assert.equal((query(read()).match(/"includedInPricing": true/g)||[]).length,2);
    query(`insert into public.conference_accommodation_rooms values('${roomNew}','${conference}','103',false,1)`);assert.equal(query(`select count(*) from public.conference_accommodation_pricing_room_exclusions where room_id='${roomNew}'`),'0');assert.match(query(read()),new RegExp(`"roomId": "${roomNew}"[\\s\\S]*?"includedInPricing": true`));
    for(const role of roles){assert.equal(query(`select has_table_privilege('${role}','public.conference_accommodation_pricing_room_exclusions','INSERT')`),'f');assert.equal(query(`select has_function_privilege('${role}','public.mutate_conference_accommodation_pricing(uuid,uuid,uuid,bigint,jsonb)','EXECUTE')`),'f');}
    rejects(`set role authenticated;insert into public.conference_accommodation_pricing_room_exclusions values('${conference}','${roomA}',now(),'${actor}')`,/permission denied/);rejects(`select public.mutate_conference_accommodation_pricing('${device}','${op()}','${conference}',0,'{}')`,/APPROVED_DEVICE_SESSION_REQUIRED|CONFERENCE_ACCOMMODATION_PRICING_ARGUMENT_INVALID|PLATFORM_OPERATION_ARGUMENT_INVALID/);
    rejects(mutate(denied,wrong,op(),0,'EXCLUDE_ROOM',roomA),/MODULE_PERMISSION_REQUIRED/);rejects(mutate(accounts,wrong,op(),0,'EXCLUDE_ROOM',roomA),/MODULE_PERMISSION_REQUIRED/);rejects(mutate(actor,revoked,op(),0,'EXCLUDE_ROOM',roomA),/APPROVED_DEVICE_SESSION_REQUIRED/);rejects(`begin;${context(actor,device)}select public.mutate_conference_accommodation_pricing('${wrong}','${op()}','${conference}',0,jsonb_build_object('action','EXCLUDE_ROOM','roomId','${roomA}'));commit;`,/APPROVED_DEVICE_SESSION_REQUIRED/);
    query(`update public.test_access set returned_actor='${denied}' where user_id='${actor}'`);rejects(mutate(actor,device,op(),0,'EXCLUDE_ROOM',roomA),/APPROVED_DEVICE_SESSION_REQUIRED|ACTOR_DEVICE_OVERRIDE_DENIED/);query(`update public.test_access set returned_actor=null where user_id='${actor}'`);
    rejects(mutate(actor,device,op(),0,'EXCLUDE_ROOM','50000000-0000-4000-8000-000000000099'),/ACCOMMODATION_ROOM_NOT_FOUND/);rejects(mutate(actor,device,op(),0,'EXCLUDE_ROOM',roomOther),/ACCOMMODATION_ROOM_NOT_FOUND/);
    const firstOp=op(),first=query(mutate(actor,device,firstOp,0,'EXCLUDE_ROOM',roomA));assert.match(first,/"includedInPricing": false/);assert.equal(query(`select revision from public.conference_accommodation_pricing where conference_id='${conference}'`),'1');assert.equal(query(mutate(actor,device,firstOp,0,'EXCLUDE_ROOM',roomA)),first);assert.equal(query(`select count(*) from platform.audit_events where operation_id='${firstOp}'`),'1');assert.equal(query(`select actor_user_id from platform.audit_events where operation_id='${firstOp}'`),actor);
    rejects(mutate(actor,device,firstOp,1,'REMOVE_ROOM_EXCLUSION',roomA),/CONFERENCE_PARTICIPATION_OPERATION_MISMATCH/);rejects(mutate(actor,device,op(),1,'EXCLUDE_ROOM',roomA),/CONFERENCE_ACCOMMODATION_PRICING_ROOM_INCLUSION_UNCHANGED/);
    const beforeLedger=query(`select count(*) from public.conference_participation_operations`),beforeAudit=query(`select count(*) from platform.audit_events`);rejects(mutate(actor,device,op(),0,'EXCLUDE_ROOM',roomB),/CONFERENCE_ACCOMMODATION_PRICING_REVISION_CONFLICT/);assert.equal(query(`select count(*) from public.conference_accommodation_pricing_room_exclusions`),'1');assert.equal(query(`select count(*) from public.conference_participation_operations`),beforeLedger);assert.equal(query(`select count(*) from platform.audit_events`),beforeAudit);
    query(mutate(actor,device,op(),1,'EXCLUDE_ROOM',roomB));assert.equal(query(`select count(*) from public.conference_accommodation_pricing_room_exclusions`),'2');query(mutate(actor,device,op(),2,'REMOVE_ROOM_EXCLUSION',roomA));assert.equal(query(`select count(*) from public.conference_accommodation_pricing_room_exclusions`),'1');assert.match(query(read()),new RegExp(`"roomId": "${roomA}"[\\s\\S]*?"includedInPricing": true`));
    query(`update public.test_access set accommodation_manage=true where user_id='${accounts}'`);query(mutate(accounts,wrong,firstOp,3,'REMOVE_ROOM_EXCLUSION',roomB));assert.equal(query(`select count(*) from public.conference_participation_operations where operation_id='${firstOp}'`),'2');query(mutate(actor,device,op(),4,'EXCLUDE_ROOM',roomB));
    query(`update public.conference_accommodation_rooms set is_closed=true where id='${roomB}'`);assert.equal(query(`select count(*) from public.conference_accommodation_pricing_room_exclusions where room_id='${roomB}'`),'1');query(`update public.conference_accommodation_rooms set is_closed=false where id='${roomB}'`);assert.equal(query(`select count(*) from public.conference_accommodation_pricing_room_exclusions where room_id='${roomB}'`),'1');query(`delete from public.conference_accommodation_rooms where id='${roomB}'`);assert.equal(query(`select count(*) from public.conference_accommodation_pricing_room_exclusions where room_id='${roomB}'`),'0');
    const failOp=op();query(`create function platform.fail_inclusion_audit() returns trigger language plpgsql as $$begin if new.operation_id='${failOp}' then raise exception 'INJECTED_INCLUSION_AUDIT_FAILURE';end if;return new;end$$;create trigger fail_inclusion_audit before insert on platform.audit_events for each row execute function platform.fail_inclusion_audit()`);rejects(mutate(actor,device,failOp,5,'EXCLUDE_ROOM',roomNew),/INJECTED_INCLUSION_AUDIT_FAILURE/);assert.equal(query(`select revision from public.conference_accommodation_pricing where conference_id='${conference}'`),'5');assert.equal(query(`select count(*) from public.conference_accommodation_pricing_room_exclusions where room_id='${roomNew}'`),'0');assert.equal(query(`select count(*) from public.conference_participation_operations where operation_id='${failOp}'`),'0');assert.equal(query(`select count(*) from platform.audit_events where operation_id='${failOp}'`),'0');
    const configuration={enabled:true,pricingMode:'per_room_night',prices:{personNight:1,roomNight:2,personDay:3,roomDay:4,packagePrice:5,packageDayPrice:6},roomTypePrices:{single:7,double:8,triple:9,quadruple:10,quintuple:11,sextuple:12,sevenPlus:13}};query(`begin;${context(actor,device)}select public.mutate_conference_accommodation_pricing('${device}','${op()}','${conference}',5,'${JSON.stringify(configuration)}'::jsonb);commit;`);assert.equal(query(`select pricing_mode||':'||revision from public.conference_accommodation_pricing where conference_id='${conference}'`),'per_room_night:6');
  }finally{command('dropdb',['--if-exists',database]);for(const role of created)command('psql',['-X','-v','ON_ERROR_STOP=1','-d','postgres','-c',`drop role ${role}`]);}
});
