'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
var root=path.resolve(__dirname,'..');
var contractSource=fs.readFileSync(path.join(root,'js/sync/conference-permission-contract.js'),'utf8');
var resolverSource=fs.readFileSync(path.join(root,'js/sync/conference-permission-resolver.js'),'utf8');
var sandbox={window:null,Object:Object,Array:Array,String:String,JSON:JSON};sandbox.window=sandbox;
vm.runInNewContext(contractSource,sandbox);vm.runInNewContext(resolverSource,sandbox);
var resolver=sandbox.ConferencePermissionResolver;
assert.strictEqual(resolver.enforcementEnabled,false);
assert.strictEqual(resolver.can('accommodation','read',{authorizationDecision:{ok:true,role:'owner'}}),false);
assert.strictEqual(resolver.canConference('conference.delete',{authorizationDecision:{ok:true,role:'owner'}}),false);
assert.strictEqual(resolver.require('accounts','delete',{}),false);
assert.strictEqual(resolver.requireConference('conference.delete',{}),false);
var result=resolver.resolveHandler('saveHouse','update',{});
assert.strictEqual(result.status,'retired');
assert.strictEqual(result.allowed,false);
assert.strictEqual(result.shouldProceed,true);
assert.deepStrictEqual(Array.from(resolver.getDiagnostics()),[]);
assert.strictEqual(sandbox.ConferencePermissionShadowGate('deleteHouse',null),true);
assert.doesNotMatch(resolverSource,/ConferenceActivationAuthorization|authorizationDecision|\.rpc\s*\(|Supabase/);
console.log('conference permission resolver retirement tests: passed');
