'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
var root=path.resolve(__dirname,'..');
var source=fs.readFileSync(path.join(root,'js/sync/conference-permission-contract.js'),'utf8');
var sandbox={window:null,Object:Object,Array:Array,String:String,JSON:JSON};sandbox.window=sandbox;
vm.runInNewContext(source,sandbox,{filename:'conference-permission-contract.js'});
var contract=sandbox.ConferencePermissionContract;
assert.strictEqual(contract.retired,true);
assert.strictEqual(contract.enforcementEnabled,false);
assert.deepStrictEqual(Array.from(contract.sections),[]);
assert.deepStrictEqual(Array.from(contract.actions),[]);
assert.deepStrictEqual(Array.from(contract.conferenceActions),[]);
assert.deepStrictEqual(Array.from(contract.roles),[]);
assert.deepStrictEqual(Object.keys(contract.roleBundles),[]);
assert.deepStrictEqual(Array.from(contract.mutationCatalog),[]);
assert.deepStrictEqual(Array.from(contract.conferenceMutationCatalog),[]);
assert.strictEqual(contract.hasSectionPermission('owner','accommodation','read'),false);
assert.strictEqual(contract.hasConferencePermission('owner','conference.delete'),false);
assert.deepStrictEqual(Array.from(contract.semanticBoundaries),['platform_permission']);
assert.ok(contract.nonAuthorizationSignals.indexOf('conference_role')>=0);
assert.strictEqual(contract.lockSemantics,'concurrency_precondition_only');
assert.doesNotMatch(source,/ROLE_BUNDLES|accommodation_viewer|transport_viewer/);
console.log('conference permission contract retirement tests: passed');
