'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
var root=path.resolve(__dirname,'..');
var source=fs.readFileSync(path.join(root,'js/sync/conference-permission-contract.js'),'utf8');
var sandbox={window:null,Object:Object,Array:Array,String:String,JSON:JSON};sandbox.window=sandbox;
vm.runInNewContext(source,sandbox);
var contract=sandbox.ConferencePermissionContract;
assert.strictEqual(contract.retired,true);
assert.deepStrictEqual(Array.from(contract.mutationCatalog),[]);
assert.deepStrictEqual(Array.from(contract.conferenceMutationCatalog),[]);
assert.deepStrictEqual(Array.from(contract.futureActionCandidates),[]);
assert.strictEqual(source.indexOf('shadowGate'),-1);
assert.strictEqual(source.indexOf('conference.edit_metadata'),-1);
assert.strictEqual(source.indexOf('conference.delete'),-1);
assert.strictEqual(source.indexOf("'owner'"),-1);
console.log('conference permission catalog retirement tests: passed');
