'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const source=fs.readFileSync(path.resolve(__dirname,'../js/supabase/legacy-conference-organization-assignment-service.js'),'utf8');
const ids={conference:'11111111-1111-4111-8111-111111111111',organization:'22222222-2222-4222-8222-222222222222',otherOrganization:'33333333-3333-4333-8333-333333333333',actor:'44444444-4444-4444-8444-444444444444',device:'55555555-5555-4555-8555-555555555555',operation:'77777777-7777-4777-8777-777777777777'};
function environment(settings={}){
  let remoteOrganization=settings.remoteOrganization||null,rpcCalls=[],operationId=null,attemptState=null;
  const attempts={get:()=>operationId?{ok:true,data:{operationId,state:attemptState}}:{ok:false,status:'not_found'},prepare:(scope,id)=>{operationId=id;attemptState='prepared';return {ok:true,data:{operationId:id,state:'prepared'}};},markUnknown:()=>{attemptState='unknown';return {ok:true};},remove:()=>{operationId=null;attemptState=null;return {ok:true};}};
  const eligible=settings.eligible===false?[]:[{organizationId:ids.organization,displayName:'Eligible',organizationStatus:'active',eligibility:true}];
  const sandbox={window:null,Promise,JSON,Object,Array,String,Date,setTimeout,clearTimeout,
    SupabaseClientLayer:{getClient:()=>({rpc:(name,args)=>{rpcCalls.push({name,args});if(name==='device_guarded_list_eligible_legacy_conference_organizations'){if(settings.preflightFailure)return Promise.resolve({data:null,error:{code:'42501',message:'LEGACY_CONFERENCE_PREFLIGHT_UNAVAILABLE'}});return Promise.resolve({data:settings.malformedPreflight||{status:'eligible_organizations',organizations:eligible},error:null});}if(settings.rpcDeferred)return settings.rpcDeferred.promise;if(settings.rpcFailure)return Promise.reject({code:'NETWORK_ERROR',message:'network'});return Promise.resolve({data:{status:'assigned',conferenceId:ids.conference,organizationId:ids.organization,operationId:args.p_operation_id}});}})},
    SupabaseAuth:{getSession:()=>({user:{id:ids.actor}})},SupabaseDeviceIdentity:{getOrCreate:()=>({id:ids.device})},CanonicalConferenceDiscovery:{listAccessibleConferences:()=>Promise.resolve({ok:true,data:{conferences:[{id:ids.conference,organizationId:remoteOrganization}]}})},LegacyConferenceOrganizationAssignmentAttemptStore:attempts,crypto:{randomUUID:()=>ids.operation}};
  sandbox.window=sandbox;vm.runInNewContext(source,sandbox);return {api:sandbox.LegacyConferenceOrganizationAssignmentService,calls:rpcCalls,setRemote:value=>{remoteOrganization=value;},setFailure:value=>{settings.rpcFailure=value;},operation:()=>operationId};
}
(async()=>{
  const env=environment(),preflight=await env.api.preflight({conferenceId:ids.conference});assert.strictEqual(preflight.status,'legacy');assert.deepStrictEqual(Array.from(preflight.data.eligibleOrganizations,item=>item.organizationId),[ids.organization]);assert.deepStrictEqual(env.calls.map(call=>call.name),['device_guarded_list_eligible_legacy_conference_organizations']);assert.deepStrictEqual(JSON.parse(JSON.stringify(env.calls[0].args)),{p_actor_device_id:ids.device,p_conference_id:ids.conference});
  const ineligible=environment({eligible:false}),blocked=await ineligible.api.assign({conferenceId:ids.conference,organizationId:ids.otherOrganization});assert.strictEqual(blocked.status,'organization_not_eligible');assert.deepStrictEqual(ineligible.calls.map(call=>call.name),['device_guarded_list_eligible_legacy_conference_organizations']);
  const assignedEnv=environment(),assigned=await assignedEnv.api.assign({conferenceId:ids.conference,organizationId:ids.organization});assert.strictEqual(assigned.ok,true);assert.deepStrictEqual(assignedEnv.calls.map(call=>call.name),['device_guarded_list_eligible_legacy_conference_organizations','device_guarded_assign_legacy_conference_organization']);assert.deepStrictEqual(JSON.parse(JSON.stringify(assignedEnv.calls[1].args)),{p_actor_device_id:ids.device,p_operation_id:ids.operation,p_conference_id:ids.conference,p_organization_id:ids.organization});
  const sanitized=environment({malformedPreflight:{status:'eligible_organizations',organizations:[{organizationId:ids.organization,displayName:'Safe',organizationStatus:'active',eligibility:true,userId:ids.actor,email:'hidden@example.invalid'}]}}),sanitizedResult=await sanitized.api.preflight({conferenceId:ids.conference});assert.strictEqual(Object.prototype.hasOwnProperty.call(sanitizedResult.data.eligibleOrganizations[0],'userId'),false);assert.strictEqual(Object.prototype.hasOwnProperty.call(sanitizedResult.data.eligibleOrganizations[0],'email'),false);
  const retry=environment({rpcFailure:true});const failed=await retry.api.assign({conferenceId:ids.conference,organizationId:ids.organization});assert.strictEqual(failed.status,'rpc_error');assert.strictEqual(retry.operation(),ids.operation);retry.setFailure(false);const replay=await retry.api.assign({conferenceId:ids.conference,organizationId:ids.organization});assert.strictEqual(replay.ok,true);const writes=retry.calls.filter(call=>call.name==='device_guarded_assign_legacy_conference_organization');assert.strictEqual(writes.length,2);assert.strictEqual(writes[0].args.p_operation_id,writes[1].args.p_operation_id);
  const readback=environment({rpcFailure:true});await readback.api.assign({conferenceId:ids.conference,organizationId:ids.organization});readback.setRemote(ids.organization);readback.setFailure(false);const recovered=await readback.api.assign({conferenceId:ids.conference,organizationId:ids.organization});assert.strictEqual(recovered.status,'assigned_after_readback');assert.strictEqual(readback.calls.filter(call=>call.name==='device_guarded_assign_legacy_conference_organization').length,1);
  let resolveRpc;const rpcDeferred={promise:new Promise(resolve=>{resolveRpc=resolve;})},doubleClick=environment({rpcDeferred});const first=doubleClick.api.assign({conferenceId:ids.conference,organizationId:ids.organization}),second=doubleClick.api.assign({conferenceId:ids.conference,organizationId:ids.organization});assert.strictEqual(first,second);await new Promise(resolve=>setImmediate(resolve));assert.strictEqual(doubleClick.calls.filter(call=>call.name==='device_guarded_assign_legacy_conference_organization').length,1);resolveRpc({data:{status:'assigned',conferenceId:ids.conference,organizationId:ids.organization,operationId:ids.operation}});await first;
  console.log('legacy conference organization assignment service tests: passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
