'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path');
var root=path.resolve(__dirname,'..');
var migration=fs.readFileSync(path.join(root,'supabase/migrations/20260805_5_4_4_multi_device_authorization.sql'),'utf8');
var ui=fs.readFileSync(path.join(root,'js/sync/device-authorization-administration-ui.js'),'utf8');
var gate=fs.readFileSync(path.join(root,'js/sync/device-reauthorization-flow.js'),'utf8');
var state=fs.readFileSync(path.join(root,'state.js'),'utf8');
var index=fs.readFileSync(path.join(root,'index.html'),'utf8');
var worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
var verification=fs.readFileSync(path.join(root,'supabase/multi-device-authorization-readonly-verification.sql'),'utf8');
assert.match(migration,/drop index if exists public\.user_device_authorizations_one_approved_per_user_idx/i);
assert.match(migration,/create index if not exists user_device_authorizations_approved_user_idx[\s\S]*authorization_status = 'approved'/i);
var approve=migration.match(/create or replace function public\.approve_member_device[\s\S]*?\n\$\$;/i)[0];
assert.match(approve,/authorization_status<>'pending'/i);
assert.match(approve,/set authorization_status='approved'/i);
assert.doesNotMatch(approve,/exists\s*\(select 1 from public\.user_device_authorizations[\s\S]*authorization_status='approved'/i);
assert.doesNotMatch(approve,/replace_member_active_device|authorization_status='revoked'/i);
assert.strictEqual((approve.match(/require_device_authorization_manager/gi)||[]).length,2,'approved actor device and organization manager must be checked before and after locks');
var revoke=migration.match(/create or replace function public\.revoke_member_device[\s\S]*?\n\$\$;/i)[0];
assert.match(revoke,/count\(\*\)[\s\S]*authorization_status='approved'[\s\S]*<=1/i);
assert.strictEqual((revoke.match(/set authorization_status='revoked'/gi)||[]).length,1);
var replace=migration.match(/create or replace function public\.replace_member_active_device[\s\S]*?\n\$\$;/i)[0];
assert.strictEqual((replace.match(/set authorization_status='revoked'/gi)||[]).length,1);
assert.strictEqual((replace.match(/set authorization_status='approved'/gi)||[]).length,1);
assert.doesNotMatch(replace,/count\(\*\)[\s\S]*authorization_status='approved'[\s\S]*<>1/i);
assert.doesNotMatch(ui,/action==='approve'&&approved\.length===1|effectiveAction='replace'/);
assert.match(ui,/replaceFrom/);
assert.match(gate,/status==='approved'/);
assert.doesNotMatch(gate,/isSoleApprovedDevice|approvedDeviceCount|count/);
assert.doesNotMatch(migration+ui,/SyncQueue|revision|ConferenceLinkStore|AutomaticSync/);
assert.match(state,/DeviceReauthorizationFlow\.waitUntilApproved/);
var devices=[{id:'windows',status:'approved'},{id:'iphone',status:'pending'}];
devices.filter(function(device){return device.id==='iphone';})[0].status='approved';
assert.deepStrictEqual(devices,[{id:'windows',status:'approved'},{id:'iphone',status:'approved'}],'owner approval must approve only the pending iPhone');
devices.filter(function(device){return device.id==='windows';})[0].status='revoked';
assert.deepStrictEqual(devices,[{id:'windows',status:'revoked'},{id:'iphone',status:'approved'}],'targeted revocation must preserve the iPhone');
['legacy_single_approved_index_removed','multi_device_approved_lookup_index_exists','approve_rpc_security_definer','approve_rpc_search_path_valid','legacy_existing_approved_rejection_removed','organization_manager_guard_present','authenticated_execute','anon_execute_denied'].forEach(function(field){assert.ok(verification.includes(field),field);});
assert.doesNotMatch(verification,/^\s*(?:insert|update|delete|create|alter|drop|grant|revoke|truncate)\b/im);
['js/sync/device-authorization-administration-ui.js?rev=startup-device-admin-lifecycle-v2'].forEach(function(asset){assert.ok(index.includes(asset),asset);assert.ok(worker.includes('./'+asset),asset);});
console.log('multi-device authorization contract tests: passed');
