'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const migration=fs.readFileSync(path.join(root,'supabase/migrations/20260811_6_7_0_organization_archive_restore.sql'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'script.js'),'utf8');
const management=fs.readFileSync(path.join(root,'js/sync/organization-management-ui.js'),'utf8');

assert.doesNotMatch(index,/id="organizationManagementTabButton"/);
assert.doesNotMatch(index,/startup-action[^>]+OrganizationManagementUI\.open/);
assert.match(app,/OrganizationManagementUI\.open\(\{returnView:\\'settings\\'\}\)/);
assert.match(app,/function closeOrganizationManagementScreen\(\)/);
assert.match(app,/function switchTab[\s\S]*closeOrganizationManagementScreen\(\)/);
assert.match(app,/capabilities\.canRestore===true/);
assert.match(management,/المؤسسات النشطة/);
assert.match(management,/المؤسسات المؤرشفة/);
assert.match(management,/OrganizationManagementUI\.restore/);
assert.match(management,/function close\(\)[\s\S]*openSettingsFromHome/);
assert.match(migration,/ARCHIVED_ORGANIZATION_READ_ONLY/);
assert.match(migration,/organization_members_reject_archived_mutation/);
console.log('organization archive lifecycle tests: passed');
