'use strict';

const assert=require('assert');
const fs=require('fs');
const path=require('path');

const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'platform-shell-v2.css'),'utf8');
const tokens=fs.readFileSync(path.join(root,'shared-design-tokens.css'),'utf8');
const warehouse=fs.readFileSync(path.join(root,'js/warehouse/workspace.js'),'utf8');
const worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');

assert.strictEqual((html.match(/class="platform-shell-v2"/g)||[]).length,1);
assert.strictEqual((html.match(/class="platform-shell-header"/g)||[]).length,1);
assert.strictEqual((html.match(/class="platform-topbar"/g)||[]).length,1);
assert.doesNotMatch(html,/startup-home-header/);
assert.match(html,/platform-shell-v2\.css\?rev=platform-dashboard-v2-v5/);
assert.match(worker,/platform-shell-v2\.css\?rev=platform-dashboard-v2-v5/);
assert.match(worker,/\? 'module-permission-lifecycle-cache-v1'/);
assert.match(html,/class="topbar conference-module-nav" id="applicationTopbar"/);
assert.match(css,/\.conference-module-nav \.application-brand-logo,\.conference-module-nav \.application-account-entry\{display:none!important\}/);
assert.match(html,/class="platform-module-switcher platform-global-nav-item" onclick="showPlatformModules\(\)"/);
assert.match(html,/class="platform-global-nav"/);
assert.strictEqual((html.match(/data-platform-module="conference"/g)||[]).length,1);
assert.strictEqual((html.match(/data-platform-module="reservations"/g)||[]).length,1);
assert.strictEqual((html.match(/data-platform-module="warehouse"/g)||[]).length,1);
assert.doesNotMatch(html,/platform-home|platform-module-grid|platform-module-card/);
assert.match(html,/platform-navigation-toggle/);
assert.match(html,/id="conferenceWorkspace"/);
assert.match(html,/id="warehouseWorkspace"/);
assert.match(html,/id="reservationsWorkspace"/);
assert.match(css,/@media\(max-width:1100px\)/);
assert.match(css,/@media\(max-width:820px\)/);
assert.match(css,/@media\(max-width:700px\)/);
assert.match(css,/@media\(max-width:600px\)/);
assert.match(css,/--platform-v2-sidebar-width\)/);
assert.match(css,/min-height:44px/);
assert.match(css,/var\(--platform-safe-area-bottom\)/);
assert.match(css,/html,body\{max-width:100%;overflow-x:hidden\}/);
assert.match(css,/@media\(max-width:820px\)[\s\S]*?#warehouseWorkspace \.warehouse-menu-trigger\{display:grid/);
assert.match(css,/@media\(max-width:600px\)[\s\S]*?font-size:16px/);
assert.match(tokens,/--platform-touch-target:44px/);
assert.match(tokens,/--platform-safe-area-bottom:max\(16px,env\(safe-area-inset-bottom,0px\)\)/);
assert.match(tokens,/--platform-shell-header-height:72px/);
assert.match(tokens,/--platform-v2-sidebar-width:288px/);
assert.match(tokens,/--platform-v2-primary:#0a6cff/);
assert.match(tokens,/--platform-v2-navy:#0b2747/);
assert.match(html,/<meta name="viewport" content="width=device-width,initial-scale=1\.0,viewport-fit=cover">/);
assert.doesNotMatch(warehouse,/class="warehouse-brand"/);
assert.doesNotMatch(warehouse,/class="warehouse-topbar"/);
assert.doesNotMatch(warehouse,/class="warehouse-account"/);
assert.doesNotMatch(warehouse,/data-wh-modules/);
assert.match(warehouse,/class="warehouse-sidebar"[\s\S]*?<nav>/);
assert.match(warehouse,/class="warehouse-menu-trigger" data-wh-menu/);
assert.match(html,/data-startup-auth-account-name/);
assert.match(html,/SyncSettingsUI\.signOut\(\)/);

console.log('platform shell v2 responsive contract tests passed');
