'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path');
var sql=fs.readFileSync(path.resolve(__dirname,'../supabase/migrations/20261009121500_final_conference_membership_consumer_demolition.sql'),'utf8');
['search_user_management_users','get_user_management_overview'].forEach(function(name){assert.match(sql,new RegExp('function\\s+public\\.'+name,'i'));});
assert.ok((sql.match(/security definer/gi)||[]).length>=3);
assert.ok((sql.match(/set search_path=''/gi)||[]).length>=3);
assert.ok((sql.match(/require_current_approved_device/gi)||[]).length>=3);
assert.ok((sql.match(/public\.is_system_owner\s*\(/gi)||[]).length>=3);
assert.match(sql,/revoke all[\s\S]+from public,anon/i);
assert.match(sql,/grant execute[\s\S]+to authenticated/i);
['accountStatus','canCreateConferences','systemRoles','organizations','deviceOrganizationId','capabilities'].forEach(function(field){assert.ok(sql.includes("'"+field+"'"),'missing '+field);});
assert.doesNotMatch(sql,/['"](?:conferenceCount|conferences|canViewConferences|canManageConferenceMembership)['"]/);
console.log('user management read contract tests: passed');
