'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
var source=fs.readFileSync(path.resolve(__dirname,'../js/sync/user-management-ui.js'),'utf8');
var user='11111111-1111-4111-8111-111111111111';
var devices=[{deviceId:'33333333-3333-4333-8333-333333333333',deviceName:'Current Device',platform:'Browser',authorizationStatus:'approved'},{deviceId:'44444444-4444-4444-8444-444444444444',deviceName:'Pending Device',platform:'Mobile',authorizationStatus:'pending'}];
var view={selectedUser:{userId:user,displayName:'Device Target',email:'device@dev.test'},account:{status:'loaded',data:{accountStatus:'approved'}},devices:{status:'loaded',managementStatus:'read_only',data:{items:devices}},capabilities:{canViewAccount:true,canViewDevices:true,canManageDevices:false}};
var read={listUsers:function(){return Promise.resolve({ok:true,data:{users:[{userId:user,displayName:'Device Target',email:'device@dev.test',accountStatus:'approved',deviceCount:2}]}});},getOverview:function(){return Promise.resolve({ok:true,data:{overview:view}});}};
var sandbox={window:{UserManagementReadService:read,document:{getElementById:function(){return null;}}},Promise:Promise};
vm.runInNewContext(source,sandbox);
(async function(){await sandbox.window.UserManagementUI.initialize();var html=sandbox.window.UserManagementUI.renderSection();assert.ok(html.includes('Current Device'));assert.ok(html.includes('Pending Device'));assert.doesNotMatch(html,/اعتماد الجهاز|رفض الطلب|إلغاء اعتماد|استبدال/);assert.doesNotMatch(source,/manageDevice|listMemberDevices|organizationId/);console.log('user management read-only device UI tests: passed');})().catch(function(error){console.error(error);process.exitCode=1;});
