'use strict';
var assert=require('assert'),fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
var source=fs.readFileSync(path.join(root,'js/sync/user-management-ui.js'),'utf8');
var index=fs.readFileSync(path.join(root,'index.html'),'utf8');
var worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
var script=fs.readFileSync(path.join(root,'script.js'),'utf8');
var style=fs.readFileSync(path.join(root,'style.css'),'utf8');
['UserSummaryCard','UserSectionCard','UserStatusBadge','UserActionBar'].forEach(function(component){assert.match(source,new RegExp('function\\s+'+component+'\\s*\\('));});
['الحساب','المؤسسة','الأجهزة'].forEach(function(section){assert.ok(source.includes(section));});
['approved','pending','blocked'].forEach(function(status){assert.ok(source.includes(status));});
assert.doesNotMatch(source,/conferenceCount|canViewConferences|canManageConferenceMembership/);assert.ok(source.includes('deviceCount'));
assert.ok(source.includes('disabled'));assert.ok(source.includes('UserManagementReadService'));
assert.ok(source.includes('initialize'));
assert.doesNotMatch(source,/prototype-user-|example\.test|var\s+USERS/);
assert.doesNotMatch(source,/\.rpc\s*\(|\.from\s*\(|\.insert\s*\(|\.update\s*\(|\.delete\s*\(/);
var asset='js/sync/user-management-ui.js?rev=organization-membership-operation-key-v1';
var serviceAsset='js/sync/user-management-read-service.js?rev=admin-session-boundary-v1';
assert.ok(index.includes('src="'+asset+'"'));assert.ok(worker.includes("'./"+asset+"'"));
assert.ok(index.includes('src="'+serviceAsset+'"'));assert.ok(worker.includes("'./"+serviceAsset+"'"));
assert.ok(index.indexOf(serviceAsset)<index.indexOf(asset));
assert.ok(script.includes("activeSettingsTab === 'users'"));
assert.ok(script.includes('window.UserManagementUI.renderSection()'));
assert.ok(script.includes('window.UserManagementUI.initialize'));
assert.ok(style.includes('.user-management-layout'));
assert.match(style,/@media\s*\(\s*max-width\s*:\s*760px\s*\)/);
console.log('user management prototype contract tests: passed');
