(function(global){
  'use strict';
  var STORE='keys';
  var PURPOSE='PLATFORM_DEVICE_SESSION_ESTABLISH';
  var ORIGIN='https://ramyawny37.github.io';
  var memorySession=null,expiryTimer=null,ensureFlight=null;

  function encoded(value){return btoa(String.fromCharCode.apply(null,new Uint8Array(value))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
  function database(){var namespace=global.PlatformDeviceStorageNamespace;if(!namespace) return Promise.reject(new Error('DEVICE_STORAGE_NAMESPACE_REQUIRED'));return new Promise(function(resolve,reject){var opening=indexedDB.open(namespace.databaseName(),1);opening.onsuccess=function(){resolve(opening.result);};opening.onerror=function(){reject(opening.error);};});}
  function loadKey(deviceId){return database().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction(STORE,'readonly'),request=tx.objectStore(STORE).getAll();request.onsuccess=function(){db.close();var rows=Array.isArray(request.result)?request.result:[];resolve(rows.find(function(row){return row&&row.state==='active'&&row.deviceId===deviceId;})||null);};request.onerror=function(){db.close();reject(request.error);};});});}
  function verifyNonExportable(key){return global.crypto.subtle.exportKey('jwk',key).then(function(){throw new Error('PRIVATE_KEY_EXPORT_SUCCEEDED');},function(){return true;});}
  function safeCode(value){var code=value&&value.error&&value.error.code;return typeof code==='string'&&/^[A-Z][A-Z0-9_]{0,95}$/.test(code)?code:null;}
  function safeText(value){return typeof value==='string'&&value.length<=300&&!/[\r\n]/.test(value)?value:null;}
  function safeProtectedError(value,status,fallback){var body=value&&value.error&&typeof value.error==='object'?value.error:{},code=safeCode(value)||fallback||'PLATFORM_DEVICE_OPERATION_DENIED',result={code:code};if(Number.isInteger(status)&&status>=400&&status<=599)result.status=status;var message=safeText(body.message),details=safeText(body.details);if(message)result.message=message;if(details)result.details=details;return result;}
  function protectedError(error){var context=error&&error.context,status=context&&Number(context.status);if(!context||typeof context.json!=='function')return Promise.resolve(safeProtectedError(null,status,'PLATFORM_DEVICE_OPERATION_DENIED'));return Promise.resolve(context.json()).then(function(body){return safeProtectedError(body,status,'PLATFORM_DEVICE_OPERATION_DENIED');},function(){return safeProtectedError(null,status,'PLATFORM_DEVICE_OPERATION_DENIED');});}
  function errorCode(error){var direct=safeCode(error);if(direct)return Promise.resolve(direct);var context=error&&error.context;if(!context||typeof context.json!=='function')return Promise.resolve(null);return Promise.resolve(context.json()).then(safeCode,function(){return null;});}
  function invoke(client,body){return client.functions.invoke('platform-device-session',{body:body}).then(function(response){if(response.error)return errorCode(response.error).then(function(code){throw {code:code||'DEVICE_SESSION_DENIED'};});if(!response.data||response.data.ok!==true)throw response.data&&response.data.error||{code:'DEVICE_SESSION_DENIED'};return response.data.data;});}
  function currentDevice(){var value=global.SupabaseDeviceIdentity&&global.SupabaseDeviceIdentity.getOrCreate&&global.SupabaseDeviceIdentity.getOrCreate();return String(value&&value.id||'');}
  function authority(record,auth,deviceId){if(!record||record.state!=='active'||record.deviceId!==deviceId||!record.bindingId||!record.privateKey)throw new Error('BOUND_PRIVATE_KEY_REQUIRED');if(!auth||!auth.authenticated||!auth.user)throw new Error('AUTH_REQUIRED');return verifyNonExportable(record.privateKey);}
  function establish(){var client=global.SupabaseClientLayer.getClient(),record,challenge,signatureBody,userId,deviceId=currentDevice();if(!client)return Promise.reject({code:'SUPABASE_CLIENT_REQUIRED'});if(!deviceId)return Promise.reject({code:'DEVICE_ID_REQUIRED'});return Promise.all([loadKey(deviceId),global.SupabaseAuth.initialize()]).then(function(values){record=values[0];userId=String(values[1]&&values[1].user&&values[1].user.id||'');return authority(record,values[1],deviceId);}).then(function(){return invoke(client,{action:'begin',bindingId:record.bindingId});}).then(function(value){challenge=value;if(challenge.userId!==userId||challenge.bindingId!==record.bindingId||challenge.deviceId!==deviceId||challenge.publicKeyThumbprint!==record.publicKeyThumbprint||challenge.purpose!==PURPOSE||challenge.origin!==ORIGIN)throw new Error('DEVICE_SESSION_CHALLENGE_MISMATCH');return global.crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},record.privateKey,new TextEncoder().encode(challenge.signingPayload));}).then(function(signature){signatureBody={action:'establish',challengeId:challenge.challengeId,signature:encoded(signature)};return invoke(client,signatureBody);}).then(function(session){memorySession={sessionId:session.sessionId,token:session.token,userId:session.userId,deviceId:session.deviceId,authorizationId:session.authorizationId,bindingId:session.bindingId,issuedAt:session.issuedAt,expiresAt:session.expiresAt};return verify().then(function(verified){return {session:copy(),verified:verified,replay:function(){return invoke(client,signatureBody).then(function(){throw new Error('REPLAY_ACCEPTED');},function(error){var value=error&&error.code||'';if(value!=='DEVICE_SESSION_CHALLENGE_INVALID')throw error;return {rejected:true,code:value};});}};});});}
  function verify(){var client=global.SupabaseClientLayer.getClient();if(!client||!memorySession)return Promise.reject({code:'DEVICE_SESSION_MISSING'});return invoke(client,{action:'verify',sessionId:memorySession.sessionId,token:memorySession.token});}
  function copy(){return memorySession?{sessionId:memorySession.sessionId,userId:memorySession.userId,deviceId:memorySession.deviceId,authorizationId:memorySession.authorizationId,bindingId:memorySession.bindingId,issuedAt:memorySession.issuedAt,expiresAt:memorySession.expiresAt}:null;}
  function clear(){memorySession=null;if(expiryTimer){global.clearTimeout(expiryTimer);expiryTimer=null;}if(global.document&&typeof global.document.dispatchEvent==='function')global.document.dispatchEvent(new CustomEvent('platform-device-session-invalid'));}
  function validFor(milliseconds){return !!(memorySession&&Date.parse(memorySession.expiresAt)-Date.now()>Number(milliseconds||0));}
  function scheduleExpiry(){if(expiryTimer)global.clearTimeout(expiryTimer);var delay=memorySession?Math.max(0,Date.parse(memorySession.expiresAt)-Date.now()):0;expiryTimer=global.setTimeout(clear,delay);}
  function ensureValid(){
    if(validFor(90000))return verify();
    if(ensureFlight)return ensureFlight;
    ensureFlight=establish().then(function(value){scheduleExpiry();ensureFlight=null;return value.verified;},function(error){ensureFlight=null;throw error;});
    return ensureFlight;
  }
  function invokeModuleProtected(module,operation,args){return ensureValid().then(function(){var client=global.SupabaseClientLayer.getClient();return client.functions.invoke('platform-device-operation',{body:{sessionId:memorySession.sessionId,token:memorySession.token,module:module,operation:operation,args:args||{}}});}).then(function(response){if(response.error)return protectedError(response.error).then(function(error){throw error;});if(!response.data||response.data.ok!==true)throw safeProtectedError(response.data,null,'PLATFORM_DEVICE_OPERATION_DENIED');return response.data.data;});}
  function invokeProtected(operation,args){return invokeModuleProtected('conference',operation,args);}
  global.PlatformDeviceSession=Object.freeze({establish:establish,ensureValid:ensureValid,validFor:validFor,invokeProtected:invokeProtected,invokeModuleProtected:invokeModuleProtected,verify:verify,getSession:copy,clear:clear});
})(window);
