begin;
do $$ begin
 if to_regclass('public.conference_accommodation_houses') is null or to_regclass('public.conference_accommodation_rooms') is null
 or to_regprocedure('platform_private.route_canonical_conference_operation(uuid,uuid,bytea,uuid,text,jsonb)') is null
 or not exists(select 1 from public.module_permission_catalog where permission_key='conference.air_conditioning.view' and status='active')
 or not exists(select 1 from public.module_permission_catalog where permission_key='conference.air_conditioning.manage' and status='active')
 then raise exception 'P6I_B4B_CANONICAL_FOUNDATION_REQUIRED' using errcode='55000'; end if;
end $$;

create table public.conference_air_conditioning_defaults(
 conference_id uuid primary key references public.conferences(id) on delete cascade,enabled boolean not null default true,
 pricing_basis text not null default 'PER_ROOM' check(pricing_basis in('PER_PERSON','PER_ROOM','PER_UNIT','FIXED','INCLUDED')),
 time_basis text not null default 'DAY' check(time_basis in('DAY','NIGHT','CONFERENCE')),
 duration_basis text not null default 'CONFERENCE' check(duration_basis in('CONFERENCE','ACTUAL_OCCUPANCY')),
 unit_price numeric(14,2) not null default 0 check(unit_price>=0),fixed_amount numeric(14,2) check(fixed_amount is null or fixed_amount>=0),
 include_empty_rooms boolean not null default false,include_closed_rooms boolean not null default false,units_count integer check(units_count is null or units_count>=0),
 revision bigint not null default 1 check(revision>=1),created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id),check((pricing_basis='FIXED')=(fixed_amount is not null))
);
create table public.conference_air_conditioning_house_overrides(
 house_id uuid primary key references public.conference_accommodation_houses(id) on delete cascade,conference_id uuid not null references public.conferences(id) on delete cascade,
 enabled boolean,pricing_basis text check(pricing_basis is null or pricing_basis in('PER_PERSON','PER_ROOM','PER_UNIT','FIXED','INCLUDED')),time_basis text check(time_basis is null or time_basis in('DAY','NIGHT','CONFERENCE')),duration_basis text check(duration_basis is null or duration_basis in('CONFERENCE','ACTUAL_OCCUPANCY')),unit_price numeric(14,2) check(unit_price is null or unit_price>=0),fixed_amount numeric(14,2) check(fixed_amount is null or fixed_amount>=0),include_empty_rooms boolean,include_closed_rooms boolean,units_count integer check(units_count is null or units_count>=0),revision bigint not null default 1 check(revision>=1),created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id),unique(house_id,conference_id),check(fixed_amount is null or pricing_basis='FIXED')
);
create table public.conference_air_conditioning_room_overrides(
 room_id uuid primary key references public.conference_accommodation_rooms(id) on delete cascade,conference_id uuid not null references public.conferences(id) on delete cascade,
 included boolean,enabled boolean,pricing_basis text check(pricing_basis is null or pricing_basis in('PER_PERSON','PER_ROOM','PER_UNIT','FIXED','INCLUDED')),time_basis text check(time_basis is null or time_basis in('DAY','NIGHT','CONFERENCE')),duration_basis text check(duration_basis is null or duration_basis in('CONFERENCE','ACTUAL_OCCUPANCY')),unit_price numeric(14,2) check(unit_price is null or unit_price>=0),fixed_amount numeric(14,2) check(fixed_amount is null or fixed_amount>=0),include_empty_rooms boolean,include_closed_rooms boolean,units_count integer check(units_count is null or units_count>=0),revision bigint not null default 1 check(revision>=1),created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id),unique(room_id,conference_id),check(fixed_amount is null or pricing_basis='FIXED')
);
alter table public.conference_air_conditioning_defaults enable row level security;alter table public.conference_air_conditioning_defaults force row level security;
alter table public.conference_air_conditioning_house_overrides enable row level security;alter table public.conference_air_conditioning_house_overrides force row level security;
alter table public.conference_air_conditioning_room_overrides enable row level security;alter table public.conference_air_conditioning_room_overrides force row level security;
revoke all on table public.conference_air_conditioning_defaults,public.conference_air_conditioning_house_overrides,public.conference_air_conditioning_room_overrides from public,anon,authenticated,service_role;
alter table public.conference_participation_operations drop constraint conference_participation_operations_operation_check;
alter table public.conference_participation_operations add constraint conference_participation_operations_operation_check check(operation in('create','create_with_person','set_status','set_guardian','delete','transport_vehicle_create','transport_vehicle_update','transport_vehicle_delete','transport_assignment_set','transport_assignment_remove','restaurant_mutation','accommodation_pricing_mutation','air_conditioning_mutation'));

create function platform_private.require_conference_air_conditioning_context(p_device uuid,p_conference uuid,p_permission text,p_mutation boolean) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare c jsonb;actor uuid;conf public.conferences%rowtype;begin if p_permission not in('conference.air_conditioning.view','conference.air_conditioning.manage') then raise exception 'CONFERENCE_AIR_CONDITIONING_ARGUMENT_INVALID' using errcode='22023';end if;c:=public.require_effective_module_permission(p_device,'conference',p_permission,'conference',p_conference::text);actor:=(c->>'actorUserId')::uuid;if platform_private.validated_phase1c_device_authorization(actor,p_device) is null then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;select * into conf from public.conferences where id=p_conference and deleted_at is null;if not found then raise exception 'CONFERENCE_NOT_FOUND' using errcode='P0002';end if;if p_mutation and conf.status<>'active' then raise exception 'COMPLETED_CONFERENCE_IMMUTABLE' using errcode='55000';end if;return c;end $$;

create function public.get_conference_air_conditioning(p_device uuid,p_conference uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare c jsonb; d jsonb; h jsonb; r jsonb;begin
 c:=platform_private.require_conference_air_conditioning_context(p_device,p_conference,'conference.air_conditioning.view',false);
 select coalesce(to_jsonb(x)-'conference_id'-'created_at'-'created_by','{}') into d from public.conference_air_conditioning_defaults x where conference_id=p_conference;
 select coalesce(jsonb_agg(to_jsonb(x)-'conference_id'-'created_at'-'created_by' order by house_id),'[]') into h from public.conference_air_conditioning_house_overrides x where conference_id=p_conference;
 select coalesce(jsonb_agg(to_jsonb(x)-'conference_id'-'created_at'-'created_by' order by room_id),'[]') into r from public.conference_air_conditioning_room_overrides x where conference_id=p_conference;
 return jsonb_build_object('conferenceId',p_conference,'defaultConfiguration',coalesce(d,jsonb_build_object('enabled',true,'pricing_basis','PER_ROOM','time_basis','DAY','duration_basis','CONFERENCE','unit_price',0,'fixed_amount',null,'include_empty_rooms',false,'include_closed_rooms',false,'units_count',null,'revision',0)),'houseOverrides',h,'roomOverrides',r);
end $$;

create function public.mutate_conference_air_conditioning(p_device uuid,p_operation_id uuid,p_conference uuid,p_scope text,p_scope_id uuid,p_action text,p_expected_revision bigint,p_configuration jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare c jsonb;s jsonb;actor uuid;authz uuid;prior public.conference_participation_operations%rowtype;req jsonb;result jsonb;current_revision bigint;begin
 if p_operation_id is null or p_conference is null or p_scope not in('CONFERENCE','HOUSE','ROOM') or p_action not in('SET','CLEAR','CLEAR_SUBTREE') or (p_action='CLEAR_SUBTREE' and p_scope<>'HOUSE') or (p_scope='CONFERENCE' and p_scope_id is not null) or (p_scope<>'CONFERENCE' and p_scope_id is null) then raise exception 'CONFERENCE_AIR_CONDITIONING_ARGUMENT_INVALID' using errcode='22023';end if;
 s:=nullif(current_setting('platform.phase1c_context',true),'')::jsonb;actor:=(s->>'user_id')::uuid;if s->>'purpose'<>'PLATFORM_DEVICE_SESSION_DISPATCH' or (s->>'device_id')::uuid is distinct from p_device then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;
 authz:=platform_private.validated_phase1c_device_authorization(actor,p_device);if authz is null then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;
 c:=platform_private.require_conference_air_conditioning_context(p_device,p_conference,'conference.air_conditioning.manage',true);
 req:=jsonb_build_object('conferenceId',p_conference,'scope',p_scope,'scopeId',p_scope_id,'action',p_action,'expectedRevision',p_expected_revision,'configuration',p_configuration);
 perform pg_advisory_xact_lock(hashtextextended(actor::text||':conference-participation:'||p_operation_id::text,0));select * into prior from public.conference_participation_operations where actor_user_id=actor and operation_id=p_operation_id;if found then if prior.operation<>'air_conditioning_mutation' or prior.request<>req then raise exception 'CONFERENCE_PARTICIPATION_OPERATION_MISMATCH' using errcode='22023';end if;return prior.result;end if;
 if p_scope='CONFERENCE' then select revision into current_revision from public.conference_air_conditioning_defaults where conference_id=p_conference for update;
 elsif p_scope='HOUSE' then perform 1 from public.conference_accommodation_houses where id=p_scope_id and conference_id=p_conference;if not found then raise exception 'CONFERENCE_ACCOMMODATION_HOUSE_NOT_FOUND' using errcode='P0002';end if;select revision into current_revision from public.conference_air_conditioning_house_overrides where house_id=p_scope_id for update;
 else perform 1 from public.conference_accommodation_rooms rr join public.conference_accommodation_floors f on f.id=rr.floor_id join public.conference_accommodation_houses h on h.id=f.house_id where rr.id=p_scope_id and h.conference_id=p_conference;if not found then raise exception 'CONFERENCE_ACCOMMODATION_ROOM_NOT_FOUND' using errcode='P0002';end if;select revision into current_revision from public.conference_air_conditioning_room_overrides where room_id=p_scope_id for update;end if;
 if current_revision is null then current_revision:=0;end if;if p_expected_revision is distinct from current_revision then raise exception 'CONFERENCE_AIR_CONDITIONING_REVISION_CONFLICT' using errcode='40001';end if;
 if p_action='CLEAR' and p_scope='CONFERENCE' then raise exception 'CONFERENCE_AIR_CONDITIONING_ARGUMENT_INVALID' using errcode='22023';end if;
 if p_action in('CLEAR','CLEAR_SUBTREE') then if p_scope='HOUSE' then if p_action='CLEAR_SUBTREE' then delete from public.conference_air_conditioning_room_overrides ro using public.conference_accommodation_rooms rr,public.conference_accommodation_floors f where ro.room_id=rr.id and rr.floor_id=f.id and f.house_id=p_scope_id;end if;delete from public.conference_air_conditioning_house_overrides where house_id=p_scope_id;else delete from public.conference_air_conditioning_room_overrides where room_id=p_scope_id;end if;
 else
  if jsonb_typeof(p_configuration)<>'object' or p_configuration ? 'manualTotal' or p_configuration ? 'dayOverrides' then raise exception 'CONFERENCE_AIR_CONDITIONING_ARGUMENT_INVALID' using errcode='22023';end if;
  if p_scope='CONFERENCE' then perform platform_private.require_exact_jsonb_keys(p_configuration,array['enabled','pricingBasis','timeBasis','durationBasis','unitPrice','fixedAmount','includeEmptyRooms','includeClosedRooms','unitsCount']);insert into public.conference_air_conditioning_defaults(conference_id,enabled,pricing_basis,time_basis,duration_basis,unit_price,fixed_amount,include_empty_rooms,include_closed_rooms,units_count,revision,created_by,updated_by) values(p_conference,(p_configuration->>'enabled')::boolean,p_configuration->>'pricingBasis',p_configuration->>'timeBasis',p_configuration->>'durationBasis',(p_configuration->>'unitPrice')::numeric,nullif(p_configuration->>'fixedAmount','')::numeric,(p_configuration->>'includeEmptyRooms')::boolean,(p_configuration->>'includeClosedRooms')::boolean,nullif(p_configuration->>'unitsCount','')::integer,1,actor,actor) on conflict(conference_id) do update set enabled=excluded.enabled,pricing_basis=excluded.pricing_basis,time_basis=excluded.time_basis,duration_basis=excluded.duration_basis,unit_price=excluded.unit_price,fixed_amount=excluded.fixed_amount,include_empty_rooms=excluded.include_empty_rooms,include_closed_rooms=excluded.include_closed_rooms,units_count=excluded.units_count,revision=public.conference_air_conditioning_defaults.revision+1,updated_at=statement_timestamp(),updated_by=actor;
  elsif p_scope='HOUSE' then perform platform_private.require_exact_jsonb_keys(p_configuration,array['enabled','pricingBasis','timeBasis','durationBasis','unitPrice','fixedAmount','includeEmptyRooms','includeClosedRooms','unitsCount']);insert into public.conference_air_conditioning_house_overrides(house_id,conference_id,enabled,pricing_basis,time_basis,duration_basis,unit_price,fixed_amount,include_empty_rooms,include_closed_rooms,units_count,revision,created_by,updated_by) values(p_scope_id,p_conference,nullif(p_configuration->>'enabled','')::boolean,nullif(p_configuration->>'pricingBasis',''),nullif(p_configuration->>'timeBasis',''),nullif(p_configuration->>'durationBasis',''),nullif(p_configuration->>'unitPrice','')::numeric,nullif(p_configuration->>'fixedAmount','')::numeric,nullif(p_configuration->>'includeEmptyRooms','')::boolean,nullif(p_configuration->>'includeClosedRooms','')::boolean,nullif(p_configuration->>'unitsCount','')::integer,1,actor,actor) on conflict(house_id) do update set enabled=excluded.enabled,pricing_basis=excluded.pricing_basis,time_basis=excluded.time_basis,duration_basis=excluded.duration_basis,unit_price=excluded.unit_price,fixed_amount=excluded.fixed_amount,include_empty_rooms=excluded.include_empty_rooms,include_closed_rooms=excluded.include_closed_rooms,units_count=excluded.units_count,revision=public.conference_air_conditioning_house_overrides.revision+1,updated_at=statement_timestamp(),updated_by=actor;
  else perform platform_private.require_exact_jsonb_keys(p_configuration,array['included','enabled','pricingBasis','timeBasis','durationBasis','unitPrice','fixedAmount','includeEmptyRooms','includeClosedRooms','unitsCount']);insert into public.conference_air_conditioning_room_overrides(room_id,conference_id,included,enabled,pricing_basis,time_basis,duration_basis,unit_price,fixed_amount,include_empty_rooms,include_closed_rooms,units_count,revision,created_by,updated_by) values(p_scope_id,p_conference,nullif(p_configuration->>'included','')::boolean,nullif(p_configuration->>'enabled','')::boolean,nullif(p_configuration->>'pricingBasis',''),nullif(p_configuration->>'timeBasis',''),nullif(p_configuration->>'durationBasis',''),nullif(p_configuration->>'unitPrice','')::numeric,nullif(p_configuration->>'fixedAmount','')::numeric,nullif(p_configuration->>'includeEmptyRooms','')::boolean,nullif(p_configuration->>'includeClosedRooms','')::boolean,nullif(p_configuration->>'unitsCount','')::integer,1,actor,actor) on conflict(room_id) do update set included=excluded.included,enabled=excluded.enabled,pricing_basis=excluded.pricing_basis,time_basis=excluded.time_basis,duration_basis=excluded.duration_basis,unit_price=excluded.unit_price,fixed_amount=excluded.fixed_amount,include_empty_rooms=excluded.include_empty_rooms,include_closed_rooms=excluded.include_closed_rooms,units_count=excluded.units_count,revision=public.conference_air_conditioning_room_overrides.revision+1,updated_at=statement_timestamp(),updated_by=actor;end if;
 end if;
 result:=public.get_conference_air_conditioning(p_device,p_conference);insert into public.conference_participation_operations(actor_user_id,operation_id,operation,request,result,created_at) values(actor,p_operation_id,'air_conditioning_mutation',req,result,statement_timestamp());insert into platform.audit_events(actor_user_id,actor_device_authorization_id,domain,module,action,entity_type,entity_id,scope_type,old_values,new_values,metadata,operation_id,source) values(actor,authz,'platform','conference','conference.air_conditioning.configuration_changed','conference_air_conditioning_configuration',coalesce(p_scope_id,p_conference),'platform',null,p_configuration,jsonb_build_object('conferenceId',p_conference,'scope',p_scope,'permissionKey','conference.air_conditioning.manage'),p_operation_id,'rpc');return result;
end $$;
revoke all on function platform_private.require_conference_air_conditioning_context(uuid,uuid,text,boolean),public.get_conference_air_conditioning(uuid,uuid),public.mutate_conference_air_conditioning(uuid,uuid,uuid,text,uuid,text,bigint,jsonb) from public,anon,authenticated,service_role;
do $$ declare sig regprocedure:='platform_private.route_canonical_conference_operation(uuid,uuid,bytea,uuid,text,jsonb)'::regprocedure;d text;marker text:='if p_operation=''mutate_conference_accommodation_pricing'' then';branch text:='if p_operation=''get_conference_air_conditioning'' then perform platform_private.require_exact_jsonb_keys(p_args,array[''p_conference_id'']);return public.get_conference_air_conditioning(p_actor_device_id,(p_args->>''p_conference_id'')::uuid);elsif p_operation=''mutate_conference_air_conditioning'' then perform platform_private.require_exact_jsonb_keys(p_args,array[''p_operation_id'',''p_conference_id'',''p_scope'',''p_scope_id'',''p_action'',''p_expected_revision'',''p_configuration'']);return public.mutate_conference_air_conditioning(p_actor_device_id,(p_args->>''p_operation_id'')::uuid,(p_args->>''p_conference_id'')::uuid,p_args->>''p_scope'',nullif(p_args->>''p_scope_id'','''')::uuid,p_args->>''p_action'',(p_args->>''p_expected_revision'')::bigint,p_args->''p_configuration'');elsif p_operation=''mutate_conference_accommodation_pricing'' then';begin d:=pg_get_functiondef(sig);if position(marker in d)=0 then raise exception 'P6I_B4B_ROUTER_PRECONDITION_FAILED' using errcode='55000';end if;execute replace(d,marker,branch);end $$;
commit;
