begin;

do $$ begin
  if to_regclass('public.conference_participations') is null or to_regclass('public.conference_participation_operations') is null
     or to_regprocedure('platform_private.route_canonical_conference_operation(uuid,uuid,bytea,uuid,text,jsonb)') is null
     or not exists(select 1 from public.module_permission_catalog where permission_key='conference.restaurant.view' and module_key='conference' and status='active')
     or not exists(select 1 from public.module_permission_catalog where permission_key='conference.restaurant.manage' and module_key='conference' and status='active') then
    raise exception 'P6I_B3_CANONICAL_FOUNDATION_REQUIRED' using errcode='55000';
  end if;
end $$;

create table public.conference_restaurant_settings(
  conference_id uuid primary key references public.conferences(id) on delete cascade,
  enabled boolean not null default true, first_meal text not null default 'dinner' check(first_meal in('breakfast','lunch','dinner')),
  last_meal text not null default 'lunch' check(last_meal in('breakfast','lunch','dinner')),
  breakfast_price numeric(12,2) not null default 0 check(breakfast_price>=0), lunch_price numeric(12,2) not null default 0 check(lunch_price>=0), dinner_price numeric(12,2) not null default 0 check(dinner_price>=0),
  revision bigint not null default 1 check(revision>=1),created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id)
);
create table public.conference_restaurant_price_overrides(
  id uuid primary key default extensions.gen_random_uuid(),conference_id uuid not null references public.conferences(id) on delete cascade,
  day_number integer not null check(day_number>=1),meal text not null check(meal in('breakfast','lunch','dinner')),price numeric(12,2) not null check(price>=0),revision bigint not null default 1 check(revision>=1),
  created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id),unique(conference_id,day_number,meal)
);
create table public.conference_restaurant_count_overrides(
  id uuid primary key default extensions.gen_random_uuid(),conference_id uuid not null references public.conferences(id) on delete cascade,
  day_number integer not null check(day_number>=1),meal text not null check(meal in('breakfast','lunch','dinner')),extra_count integer not null default 0 check(extra_count>=0),deduction_count integer not null default 0 check(deduction_count>=0),note text check(note is null or length(note)<=120),revision bigint not null default 1 check(revision>=1),
  created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id),unique(conference_id,day_number,meal),check(extra_count>0 or deduction_count>0)
);
create table public.conference_restaurant_participation_overrides(
  id uuid primary key default extensions.gen_random_uuid(),conference_id uuid not null references public.conferences(id) on delete cascade,participation_id uuid not null,
  day_number integer not null check(day_number>=1),meal text not null check(meal in('breakfast','lunch','dinner')),included boolean not null,note text check(note is null or length(note)<=120),revision bigint not null default 1 check(revision>=1),
  created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id),
  foreign key(participation_id,conference_id) references public.conference_participations(id,conference_id) on delete restrict,unique(conference_id,participation_id,day_number,meal)
);
create index conference_restaurant_participation_overrides_participation_idx on public.conference_restaurant_participation_overrides(participation_id,id);

alter table public.conference_restaurant_settings enable row level security;alter table public.conference_restaurant_settings force row level security;
alter table public.conference_restaurant_price_overrides enable row level security;alter table public.conference_restaurant_price_overrides force row level security;
alter table public.conference_restaurant_count_overrides enable row level security;alter table public.conference_restaurant_count_overrides force row level security;
alter table public.conference_restaurant_participation_overrides enable row level security;alter table public.conference_restaurant_participation_overrides force row level security;
revoke all on table public.conference_restaurant_settings,public.conference_restaurant_price_overrides,public.conference_restaurant_count_overrides,public.conference_restaurant_participation_overrides from public,anon,authenticated,service_role;

alter table public.conference_participation_operations drop constraint conference_participation_operations_operation_check;
alter table public.conference_participation_operations add constraint conference_participation_operations_operation_check check(operation in('create','create_with_person','set_status','set_guardian','delete','transport_vehicle_create','transport_vehicle_update','transport_vehicle_delete','transport_assignment_set','transport_assignment_remove','restaurant_mutation'));

create function platform_private.require_conference_restaurant_context(p_device uuid,p_conference uuid,p_permission text,p_mutation boolean)
returns jsonb language plpgsql stable security definer set search_path='' as $$ declare c jsonb; actor uuid; conf public.conferences%rowtype; begin
  if p_permission not in('conference.restaurant.view','conference.restaurant.manage') then raise exception 'CONFERENCE_RESTAURANT_ARGUMENT_INVALID' using errcode='22023';end if;
  c:=public.require_effective_module_permission(p_device,'conference',p_permission,'conference',p_conference::text);actor:=(c->>'actorUserId')::uuid;
  if platform_private.validated_phase1c_device_authorization(actor,p_device) is null then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;
  select * into conf from public.conferences where id=p_conference and deleted_at is null;if not found then raise exception 'CONFERENCE_NOT_FOUND' using errcode='P0002';end if;
  if p_mutation and conf.status<>'active' then raise exception 'COMPLETED_CONFERENCE_IMMUTABLE' using errcode='55000';end if;return c;
end $$;

create function public.get_conference_restaurant(p_device uuid,p_conference uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $$ declare c jsonb;s public.conference_restaurant_settings%rowtype;can_manage boolean:=false;begin
  c:=platform_private.require_conference_restaurant_context(p_device,p_conference,'conference.restaurant.view',false);
  begin perform public.require_effective_module_permission(p_device,'conference','conference.restaurant.manage','conference',p_conference::text);can_manage:=true;exception when insufficient_privilege then null;end;
  select * into s from public.conference_restaurant_settings where conference_id=p_conference;
  return jsonb_build_object('conferenceId',p_conference,'canManage',can_manage,'settings',jsonb_build_object('enabled',coalesce(s.enabled,true),'firstMeal',coalesce(s.first_meal,'dinner'),'lastMeal',coalesce(s.last_meal,'lunch'),'prices',jsonb_build_object('breakfast',coalesce(s.breakfast_price,0),'lunch',coalesce(s.lunch_price,0),'dinner',coalesce(s.dinner_price,0)),'revision',coalesce(s.revision,0)),
    'priceOverrides',coalesce((select jsonb_agg(jsonb_build_object('id',id,'day',day_number,'meal',meal,'price',price,'revision',revision) order by day_number,meal) from public.conference_restaurant_price_overrides where conference_id=p_conference),'[]'),
    'countOverrides',coalesce((select jsonb_agg(jsonb_build_object('id',id,'day',day_number,'meal',meal,'extra',extra_count,'deduction',deduction_count,'note',note,'revision',revision) order by day_number,meal) from public.conference_restaurant_count_overrides where conference_id=p_conference),'[]'),
    'participationOverrides',coalesce((select jsonb_agg(jsonb_build_object('id',o.id,'participationId',o.participation_id,'day',o.day_number,'meal',o.meal,'included',o.included,'note',o.note,'revision',o.revision) order by o.day_number,o.meal,o.participation_id) from public.conference_restaurant_participation_overrides o where o.conference_id=p_conference),'[]'),
    'participations',coalesce((select jsonb_agg(jsonb_build_object('participationId',p.id,'status',p.status,'person',jsonb_build_object('personId',person.id,'fullName',person.full_name,'phone',person.phone),'roomNumber',room.room_number) order by person.full_name,p.id) from public.conference_participations p join platform.people person on person.id=p.person_id left join public.conference_accommodation_occupancies occupancy on occupancy.participation_id=p.id left join public.conference_accommodation_rooms room on room.id=occupancy.room_id where p.conference_id=p_conference),'[]'));
end $$;

create function public.mutate_conference_restaurant(p_device uuid,p_operation_id uuid,p_operation text,p_conference uuid,p_expected_revision bigint,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$ declare c jsonb;actor uuid;authz uuid;req jsonb;prior public.conference_participation_operations%rowtype;old jsonb;result jsonb;entity uuid;rev bigint;maximum_day integer;begin
  if p_operation_id is null or p_operation not in('update_settings','upsert_price','delete_price','upsert_count','delete_count','upsert_participation','delete_participation') or jsonb_typeof(p_payload)<>'object' then raise exception 'CONFERENCE_RESTAURANT_ARGUMENT_INVALID' using errcode='22023';end if;
  c:=platform_private.require_conference_restaurant_context(p_device,p_conference,'conference.restaurant.manage',true);actor:=(c->>'actorUserId')::uuid;authz:=platform_private.validated_phase1c_device_authorization(actor,p_device);req:=jsonb_build_object('operation',p_operation,'conferenceId',p_conference,'expectedRevision',p_expected_revision,'payload',p_payload);
  perform pg_advisory_xact_lock(hashtextextended(actor::text||':conference-participation:'||p_operation_id::text,0));select * into prior from public.conference_participation_operations where actor_user_id=actor and operation_id=p_operation_id;
  if found then if prior.operation<>'restaurant_mutation' or prior.request<>req then raise exception 'CONFERENCE_PARTICIPATION_OPERATION_MISMATCH' using errcode='22023';end if;return prior.result;end if;
  if p_operation='update_settings' then
    perform platform_private.require_exact_jsonb_keys(p_payload,array['enabled','firstMeal','lastMeal','prices']);perform platform_private.require_exact_jsonb_keys(p_payload->'prices',array['breakfast','lunch','dinner']);
    insert into public.conference_restaurant_settings(conference_id,enabled,first_meal,last_meal,breakfast_price,lunch_price,dinner_price,created_by,updated_by) values(p_conference,coalesce((p_payload->>'enabled')::boolean,true),p_payload->>'firstMeal',p_payload->>'lastMeal',(p_payload->'prices'->>'breakfast')::numeric,(p_payload->'prices'->>'lunch')::numeric,(p_payload->'prices'->>'dinner')::numeric,actor,actor)
    on conflict(conference_id) do update set enabled=excluded.enabled,first_meal=excluded.first_meal,last_meal=excluded.last_meal,breakfast_price=excluded.breakfast_price,lunch_price=excluded.lunch_price,dinner_price=excluded.dinner_price,revision=conference_restaurant_settings.revision+1,updated_at=statement_timestamp(),updated_by=actor where p_expected_revision=conference_restaurant_settings.revision returning conference_id,revision into entity,rev;
  elsif p_operation like '%price' then
    perform platform_private.require_exact_jsonb_keys(p_payload,case when p_operation='upsert_price' then array['day','meal','price'] else array['day','meal'] end);select (end_date-start_date)+1 into maximum_day from public.conferences where id=p_conference;if (p_payload->>'day')::integer not between 1 and maximum_day then raise exception 'CONFERENCE_RESTAURANT_DAY_INVALID' using errcode='22023';end if;
    select to_jsonb(x),x.id,x.revision into old,entity,rev from public.conference_restaurant_price_overrides x where conference_id=p_conference and day_number=(p_payload->>'day')::integer and meal=p_payload->>'meal' for update;
    if p_operation='delete_price' then if entity is null then raise exception 'CONFERENCE_RESTAURANT_NOT_FOUND' using errcode='P0002';end if;if rev<>p_expected_revision then raise exception 'CONFERENCE_RESTAURANT_REVISION_CONFLICT' using errcode='40001';end if;delete from public.conference_restaurant_price_overrides where id=entity;
    elsif entity is null then insert into public.conference_restaurant_price_overrides(conference_id,day_number,meal,price,created_by,updated_by) values(p_conference,(p_payload->>'day')::integer,p_payload->>'meal',(p_payload->>'price')::numeric,actor,actor) returning id,revision into entity,rev;
    else if rev<>p_expected_revision then raise exception 'CONFERENCE_RESTAURANT_REVISION_CONFLICT' using errcode='40001';end if;update public.conference_restaurant_price_overrides set price=(p_payload->>'price')::numeric,revision=revision+1,updated_at=statement_timestamp(),updated_by=actor where id=entity returning revision into rev;end if;
  elsif p_operation like '%count' then
    perform platform_private.require_exact_jsonb_keys(p_payload,case when p_operation='upsert_count' then array['day','meal','extra','deduction','note'] else array['day','meal'] end);select (end_date-start_date)+1 into maximum_day from public.conferences where id=p_conference;if (p_payload->>'day')::integer not between 1 and maximum_day then raise exception 'CONFERENCE_RESTAURANT_DAY_INVALID' using errcode='22023';end if;
    select to_jsonb(x),x.id,x.revision into old,entity,rev from public.conference_restaurant_count_overrides x where conference_id=p_conference and day_number=(p_payload->>'day')::integer and meal=p_payload->>'meal' for update;
    if p_operation='delete_count' then if entity is null then raise exception 'CONFERENCE_RESTAURANT_NOT_FOUND' using errcode='P0002';end if;if rev<>p_expected_revision then raise exception 'CONFERENCE_RESTAURANT_REVISION_CONFLICT' using errcode='40001';end if;delete from public.conference_restaurant_count_overrides where id=entity;
    elsif entity is null then insert into public.conference_restaurant_count_overrides(conference_id,day_number,meal,extra_count,deduction_count,note,created_by,updated_by) values(p_conference,(p_payload->>'day')::integer,p_payload->>'meal',(p_payload->>'extra')::integer,(p_payload->>'deduction')::integer,nullif(p_payload->>'note',''),actor,actor) returning id,revision into entity,rev;
    else if rev<>p_expected_revision then raise exception 'CONFERENCE_RESTAURANT_REVISION_CONFLICT' using errcode='40001';end if;update public.conference_restaurant_count_overrides set extra_count=(p_payload->>'extra')::integer,deduction_count=(p_payload->>'deduction')::integer,note=nullif(p_payload->>'note',''),revision=revision+1,updated_at=statement_timestamp(),updated_by=actor where id=entity returning revision into rev;end if;
  else
    perform platform_private.require_exact_jsonb_keys(p_payload,case when p_operation='upsert_participation' then array['participationId','day','meal','included','note'] else array['participationId','day','meal'] end);select (end_date-start_date)+1 into maximum_day from public.conferences where id=p_conference;if (p_payload->>'day')::integer not between 1 and maximum_day or not exists(select 1 from public.conference_participations where id=(p_payload->>'participationId')::uuid and conference_id=p_conference and status='active') then raise exception 'CONFERENCE_RESTAURANT_PARTICIPATION_INELIGIBLE' using errcode='23514';end if;
    select to_jsonb(x),x.id,x.revision into old,entity,rev from public.conference_restaurant_participation_overrides x where conference_id=p_conference and participation_id=(p_payload->>'participationId')::uuid and day_number=(p_payload->>'day')::integer and meal=p_payload->>'meal' for update;
    if p_operation='delete_participation' then if entity is null then raise exception 'CONFERENCE_RESTAURANT_NOT_FOUND' using errcode='P0002';end if;if rev<>p_expected_revision then raise exception 'CONFERENCE_RESTAURANT_REVISION_CONFLICT' using errcode='40001';end if;delete from public.conference_restaurant_participation_overrides where id=entity;
    elsif entity is null then insert into public.conference_restaurant_participation_overrides(conference_id,participation_id,day_number,meal,included,note,created_by,updated_by) values(p_conference,(p_payload->>'participationId')::uuid,(p_payload->>'day')::integer,p_payload->>'meal',(p_payload->>'included')::boolean,nullif(p_payload->>'note',''),actor,actor) returning id,revision into entity,rev;
    else if rev<>p_expected_revision then raise exception 'CONFERENCE_RESTAURANT_REVISION_CONFLICT' using errcode='40001';end if;update public.conference_restaurant_participation_overrides set included=(p_payload->>'included')::boolean,note=nullif(p_payload->>'note',''),revision=revision+1,updated_at=statement_timestamp(),updated_by=actor where id=entity returning revision into rev;end if;
  end if;
  if entity is null then raise exception 'CONFERENCE_RESTAURANT_REVISION_CONFLICT' using errcode='40001';end if;result:=jsonb_build_object('conferenceId',p_conference,'entityId',entity,'operation',p_operation,'revision',rev,'deleted',p_operation like 'delete_%');
  insert into public.conference_participation_operations(actor_user_id,operation_id,operation,request,result,created_at) values(actor,p_operation_id,'restaurant_mutation',req,result,statement_timestamp());
  insert into platform.audit_events(actor_user_id,actor_device_authorization_id,domain,module,action,entity_type,entity_id,scope_type,old_values,new_values,metadata,operation_id,source) values(actor,authz,'platform','conference','conference.restaurant.'||p_operation,'conference_restaurant_fact',entity,'platform',old,case when p_operation like 'delete_%' then null else p_payload end,jsonb_build_object('conferenceId',p_conference,'permissionKey','conference.restaurant.manage'),p_operation_id,'rpc');return result;
end $$;

alter function public.delete_conference_participation(uuid,uuid,uuid,bigint) rename to delete_conference_participation_without_restaurant_cleanup;
create function public.delete_conference_participation(p_actor_device_id uuid,p_operation_id uuid,p_participation_id uuid,p_expected_revision bigint) returns jsonb language plpgsql security definer set search_path='' as $$ declare ctx jsonb;actor uuid;authz uuid;prior public.conference_participation_operations%rowtype;r public.conference_restaurant_participation_overrides%rowtype;result jsonb;begin
  ctx:=nullif(current_setting('platform.phase1c_context',true),'')::jsonb;actor:=(ctx->>'user_id')::uuid;if ctx->>'purpose'<>'PLATFORM_DEVICE_SESSION_DISPATCH' or (ctx->>'device_id')::uuid is distinct from p_actor_device_id then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;authz:=platform_private.validated_phase1c_device_authorization(actor,p_actor_device_id);if authz is null then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;
  perform pg_advisory_xact_lock(hashtextextended(actor::text||':conference-participation:'||p_operation_id::text,0));select * into prior from public.conference_participation_operations where actor_user_id=actor and operation_id=p_operation_id;if found then if prior.operation<>'delete' or prior.request<>jsonb_build_object('participationId',p_participation_id,'expectedRevision',p_expected_revision) then raise exception 'CONFERENCE_PARTICIPATION_OPERATION_MISMATCH' using errcode='22023';end if;perform platform_private.require_conference_participation_context(p_actor_device_id,(prior.result->>'conferenceId')::uuid,'conference.people.manage',false);return prior.result;end if;
  for r in select o.* from public.conference_restaurant_participation_overrides o join public.conference_participations p on p.id=o.participation_id where p.id=p_participation_id or p.guardian_participation_id=p_participation_id order by o.id for update loop
    insert into platform.audit_events(actor_user_id,actor_device_authorization_id,domain,module,action,entity_type,entity_id,scope_type,old_values,new_values,metadata,operation_id,source) values(actor,authz,'platform','conference','conference.restaurant.participation_override_removed','conference_restaurant_participation_override',r.id,'platform',to_jsonb(r),null,jsonb_build_object('conferenceId',r.conference_id,'reason','participation_deleted','permissionKey','conference.people.manage'),p_operation_id,'rpc');delete from public.conference_restaurant_participation_overrides where id=r.id;
  end loop;
  result:=public.delete_conference_participation_without_restaurant_cleanup(p_actor_device_id,p_operation_id,p_participation_id,p_expected_revision);return result;
end $$;

revoke all on function platform_private.require_conference_restaurant_context(uuid,uuid,text,boolean),public.get_conference_restaurant(uuid,uuid),public.mutate_conference_restaurant(uuid,uuid,text,uuid,bigint,jsonb),public.delete_conference_participation_without_restaurant_cleanup(uuid,uuid,uuid,bigint),public.delete_conference_participation(uuid,uuid,uuid,bigint) from public,anon,authenticated,service_role;
do $$ declare sig regprocedure:='platform_private.route_canonical_conference_operation(uuid,uuid,bytea,uuid,text,jsonb)'::regprocedure;d text;marker text:='if p_operation=''get_conference_transport'' then';branch text:='if p_operation=''get_conference_restaurant'' then perform platform_private.require_exact_jsonb_keys(p_args,array[''p_conference_id'']);return public.get_conference_restaurant(p_actor_device_id,(p_args->>''p_conference_id'')::uuid);elsif p_operation=''mutate_conference_restaurant'' then perform platform_private.require_exact_jsonb_keys(p_args,array[''p_operation_id'',''p_operation'',''p_conference_id'',''p_expected_revision'',''p_payload'']);return public.mutate_conference_restaurant(p_actor_device_id,(p_args->>''p_operation_id'')::uuid,p_args->>''p_operation'',(p_args->>''p_conference_id'')::uuid,nullif(p_args->>''p_expected_revision'','''')::bigint,p_args->''p_payload'');elsif p_operation=''get_conference_transport'' then';begin d:=pg_get_functiondef(sig);if position(marker in d)=0 then raise exception 'P6I_B3_ROUTER_PRECONDITION_FAILED' using errcode='55000';end if;execute replace(d,marker,branch);end $$;

comment on table public.conference_restaurant_participation_overrides is 'Canonical Restaurant meal inclusion decision keyed only by Conference Participation; Accommodation is optional display context.';
commit;
