begin;
do $$ begin
 if to_regprocedure('platform_private.route_canonical_conference_operation(uuid,uuid,bytea,uuid,text,jsonb)') is null
 or not exists(select 1 from public.module_permission_catalog where permission_key='conference.accounts.view' and status='active')
 or not exists(select 1 from public.module_permission_catalog where permission_key='conference.accounts.manage' and status='active')
 then raise exception 'P6I_B4C_CANONICAL_FOUNDATION_REQUIRED' using errcode='55000'; end if;
end $$;

create table public.conference_finance_settings(
 conference_id uuid primary key references public.conferences(id) on delete cascade,
 currency text not null default 'EGP' check(length(btrim(currency)) between 1 and 12),rounding_precision smallint not null default 2 check(rounding_precision between 0 and 6),
 expenses_enabled boolean not null default true,income_enabled boolean not null default true,settlements_enabled boolean not null default true,adjustments_enabled boolean not null default true,
 revision bigint not null default 1 check(revision>=1),created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id)
);
create table public.conference_finance_items(
 id uuid primary key,conference_id uuid not null references public.conferences(id) on delete cascade,kind text not null check(kind in('EXPENSE','INCOME','SETTLEMENT')),
 name text not null default '',enabled boolean not null default true,calculation_method text not null check(calculation_method in('fixed','quantity_price','per_day','per_room','per_person','manual')),
 target text check(target is null or target in('expense','income')),operation text check(operation is null or operation in('add','subtract')),
 quantity numeric(14,2) check(quantity is null or quantity>=0),unit_price numeric(14,2) check(unit_price is null or unit_price>=0),amount numeric(14,2) check(amount is null or amount>=0),notes text not null default '',
 revision bigint not null default 1 check(revision>=1),created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id),
 unique(conference_id,id),check((kind='SETTLEMENT')=(target is not null and operation is not null))
);
create table public.conference_finance_adjustments(
 id uuid primary key,conference_id uuid not null references public.conferences(id) on delete cascade,type text not null check(type in('addition','deduction')),category text not null check(category in('accommodation','restaurant','air_conditioning','other')),amount numeric(14,2) not null check(amount>0),note text not null default '',revision bigint not null default 1 check(revision>=1),created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),created_by uuid not null references platform.profiles(user_id),updated_by uuid not null references platform.profiles(user_id),unique(conference_id,id)
);
alter table public.conference_finance_settings enable row level security;alter table public.conference_finance_settings force row level security;
alter table public.conference_finance_items enable row level security;alter table public.conference_finance_items force row level security;
alter table public.conference_finance_adjustments enable row level security;alter table public.conference_finance_adjustments force row level security;
revoke all on table public.conference_finance_settings,public.conference_finance_items,public.conference_finance_adjustments from public,anon,authenticated,service_role;
insert into public.conference_finance_settings(conference_id,currency,rounding_precision,expenses_enabled,income_enabled,settlements_enabled,adjustments_enabled,created_by,updated_by)
select c.id,coalesce(nullif(btrim(s.data#>>'{accounts,settings,currency}'),''),'EGP'),greatest(0,least(6,coalesce((s.data#>>'{accounts,settings,roundingPrecision}')::smallint,2))),coalesce((s.data#>>'{accounts,financialItems,enabled}')::boolean,true),coalesce((s.data#>>'{accounts,incomeItems,enabled}')::boolean,true),coalesce((s.data#>>'{accounts,settlements,enabled}')::boolean,true),coalesce((s.data#>>'{financialV3,enabled}')::boolean,true),c.owner_id,c.owner_id from public.conferences c join public.conference_snapshots s on s.conference_id=c.id where exists(select 1 from platform.profiles p where p.user_id=c.owner_id) on conflict(conference_id) do nothing;
insert into public.conference_finance_items(id,conference_id,kind,name,enabled,calculation_method,target,operation,quantity,unit_price,amount,notes,created_by,updated_by)
select (x.value->>'id')::uuid,c.id,k.kind,coalesce(x.value->>'name',''),coalesce((x.value->>'enabled')::boolean,true),case when x.value->>'calculationMethod' in('fixed','quantity_price','per_day','per_room','per_person','manual') then x.value->>'calculationMethod' else 'fixed' end,case when k.kind='SETTLEMENT' then coalesce(nullif(x.value->>'target',''),'expense') end,case when k.kind='SETTLEMENT' then coalesce(nullif(x.value->>'operation',''),'add') end,nullif(x.value->>'quantity','')::numeric,nullif(x.value->>'unitPrice','')::numeric,nullif(x.value->>'amount','')::numeric,coalesce(x.value->>'notes',''),c.owner_id,c.owner_id from public.conferences c join public.conference_snapshots s on s.conference_id=c.id cross join lateral (values('EXPENSE',s.data#>'{accounts,financialItems,items}'),('INCOME',s.data#>'{accounts,incomeItems,items}'),('SETTLEMENT',s.data#>'{accounts,settlements,items}')) k(kind,data) cross join lateral jsonb_array_elements(case when jsonb_typeof(k.data)='array' then k.data else '[]'::jsonb end) x(value) where x.value->>'id' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and exists(select 1 from platform.profiles p where p.user_id=c.owner_id) on conflict(id) do nothing;
insert into public.conference_finance_adjustments(id,conference_id,type,category,amount,note,created_by,updated_by)
select (x.value->>'id')::uuid,c.id,case when x.value->>'type'='deduction' then 'deduction' else 'addition' end,case when x.value->>'category' in('accommodation','restaurant','air_conditioning','other') then x.value->>'category' else 'other' end,(x.value->>'amount')::numeric,coalesce(x.value->>'note',''),c.owner_id,c.owner_id from public.conferences c join public.conference_snapshots s on s.conference_id=c.id cross join lateral jsonb_array_elements(case when jsonb_typeof(s.data#>'{financialV3,adjustments}')='array' then s.data#>'{financialV3,adjustments}' else '[]'::jsonb end) x(value) where x.value->>'id' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and coalesce(nullif(x.value->>'amount','')::numeric,0)>0 and exists(select 1 from platform.profiles p where p.user_id=c.owner_id) on conflict(id) do nothing;
alter table public.conference_participation_operations drop constraint conference_participation_operations_operation_check;
alter table public.conference_participation_operations add constraint conference_participation_operations_operation_check check(operation in('create','create_with_person','set_status','set_guardian','delete','transport_vehicle_create','transport_vehicle_update','transport_vehicle_delete','transport_assignment_set','transport_assignment_remove','restaurant_mutation','accommodation_pricing_mutation','air_conditioning_mutation','finance_mutation'));

create function platform_private.require_conference_finance_context(p_device uuid,p_conference uuid,p_permission text,p_mutation boolean) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare c jsonb;actor uuid;conf public.conferences%rowtype;begin if p_permission not in('conference.accounts.view','conference.accounts.manage') then raise exception 'CONFERENCE_FINANCE_ARGUMENT_INVALID' using errcode='22023';end if;c:=public.require_effective_module_permission(p_device,'conference',p_permission,'conference',p_conference::text);actor:=(c->>'actorUserId')::uuid;if platform_private.validated_phase1c_device_authorization(actor,p_device) is null then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;select * into conf from public.conferences where id=p_conference and deleted_at is null;if not found then raise exception 'CONFERENCE_NOT_FOUND' using errcode='P0002';end if;if p_mutation and conf.status<>'active' then raise exception 'COMPLETED_CONFERENCE_IMMUTABLE' using errcode='55000';end if;return c;end $$;

create function platform_private.conference_finance_projection(p_conference uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare s jsonb;i jsonb;a jsonb;begin
 select coalesce(to_jsonb(x)-'conference_id'-'created_at'-'created_by','{}') into s from public.conference_finance_settings x where conference_id=p_conference;
 select coalesce(jsonb_agg(to_jsonb(x)-'conference_id'-'created_at'-'created_by' order by kind,id),'[]') into i from public.conference_finance_items x where conference_id=p_conference;
 select coalesce(jsonb_agg(to_jsonb(x)-'conference_id'-'created_at'-'created_by' order by id),'[]') into a from public.conference_finance_adjustments x where conference_id=p_conference;
 return jsonb_build_object('conferenceId',p_conference,'settings',coalesce(s,jsonb_build_object('currency','EGP','rounding_precision',2,'expenses_enabled',true,'income_enabled',true,'settlements_enabled',true,'adjustments_enabled',true,'revision',0)),'items',i,'adjustments',a);
end $$;
create function public.get_conference_finance(p_device uuid,p_conference uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
begin perform platform_private.require_conference_finance_context(p_device,p_conference,'conference.accounts.view',false);return platform_private.conference_finance_projection(p_conference);end $$;

create function public.mutate_conference_finance(p_device uuid,p_operation_id uuid,p_conference uuid,p_entity text,p_action text,p_entity_id uuid,p_expected_revision bigint,p_payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare c jsonb;s jsonb;actor uuid;authz uuid;prior public.conference_participation_operations%rowtype;req jsonb;result jsonb;current_revision bigint;begin
 if p_operation_id is null or p_conference is null or p_entity not in('SETTINGS','EXPENSE','INCOME','SETTLEMENT','ADJUSTMENT') or p_action not in('UPSERT','DELETE') or (p_entity='SETTINGS' and (p_action<>'UPSERT' or p_entity_id is not null)) or (p_entity<>'SETTINGS' and p_entity_id is null) then raise exception 'CONFERENCE_FINANCE_ARGUMENT_INVALID' using errcode='22023';end if;
 s:=nullif(current_setting('platform.phase1c_context',true),'')::jsonb;actor:=(s->>'user_id')::uuid;if s->>'purpose'<>'PLATFORM_DEVICE_SESSION_DISPATCH' or (s->>'device_id')::uuid is distinct from p_device then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;authz:=platform_private.validated_phase1c_device_authorization(actor,p_device);if authz is null then raise exception 'APPROVED_DEVICE_SESSION_REQUIRED' using errcode='42501';end if;
 c:=platform_private.require_conference_finance_context(p_device,p_conference,'conference.accounts.manage',true);req:=jsonb_build_object('conferenceId',p_conference,'entity',p_entity,'action',p_action,'entityId',p_entity_id,'expectedRevision',p_expected_revision,'payload',p_payload);
 perform pg_advisory_xact_lock(hashtextextended(actor::text||':conference-participation:'||p_operation_id::text,0));select * into prior from public.conference_participation_operations where actor_user_id=actor and operation_id=p_operation_id;if found then if prior.operation<>'finance_mutation' or prior.request<>req then raise exception 'CONFERENCE_PARTICIPATION_OPERATION_MISMATCH' using errcode='22023';end if;return prior.result;end if;
 if p_entity='SETTINGS' then select revision into current_revision from public.conference_finance_settings where conference_id=p_conference for update;else if p_entity='ADJUSTMENT' then select revision into current_revision from public.conference_finance_adjustments where conference_id=p_conference and id=p_entity_id for update;else select revision into current_revision from public.conference_finance_items where conference_id=p_conference and id=p_entity_id for update;end if;end if;current_revision:=coalesce(current_revision,0);if p_expected_revision is distinct from current_revision then raise exception 'CONFERENCE_FINANCE_REVISION_CONFLICT' using errcode='40001';end if;
 if p_action='DELETE' then if p_entity='ADJUSTMENT' then delete from public.conference_finance_adjustments where conference_id=p_conference and id=p_entity_id;else delete from public.conference_finance_items where conference_id=p_conference and id=p_entity_id;end if;
 elsif p_entity='SETTINGS' then perform platform_private.require_exact_jsonb_keys(p_payload,array['currency','roundingPrecision','expensesEnabled','incomeEnabled','settlementsEnabled','adjustmentsEnabled']);insert into public.conference_finance_settings(conference_id,currency,rounding_precision,expenses_enabled,income_enabled,settlements_enabled,adjustments_enabled,revision,created_by,updated_by) values(p_conference,btrim(p_payload->>'currency'),(p_payload->>'roundingPrecision')::smallint,(p_payload->>'expensesEnabled')::boolean,(p_payload->>'incomeEnabled')::boolean,(p_payload->>'settlementsEnabled')::boolean,(p_payload->>'adjustmentsEnabled')::boolean,1,actor,actor) on conflict(conference_id) do update set currency=excluded.currency,rounding_precision=excluded.rounding_precision,expenses_enabled=excluded.expenses_enabled,income_enabled=excluded.income_enabled,settlements_enabled=excluded.settlements_enabled,adjustments_enabled=excluded.adjustments_enabled,revision=public.conference_finance_settings.revision+1,updated_at=statement_timestamp(),updated_by=actor;
 elsif p_entity='ADJUSTMENT' then perform platform_private.require_exact_jsonb_keys(p_payload,array['type','category','amount','note']);insert into public.conference_finance_adjustments(id,conference_id,type,category,amount,note,revision,created_by,updated_by) values(p_entity_id,p_conference,p_payload->>'type',p_payload->>'category',(p_payload->>'amount')::numeric,coalesce(p_payload->>'note',''),1,actor,actor) on conflict(id) do update set type=excluded.type,category=excluded.category,amount=excluded.amount,note=excluded.note,revision=public.conference_finance_adjustments.revision+1,updated_at=statement_timestamp(),updated_by=actor where public.conference_finance_adjustments.conference_id=p_conference;
 else perform platform_private.require_exact_jsonb_keys(p_payload,array['name','enabled','calculationMethod','target','operation','quantity','unitPrice','amount','notes']);insert into public.conference_finance_items(id,conference_id,kind,name,enabled,calculation_method,target,operation,quantity,unit_price,amount,notes,revision,created_by,updated_by) values(p_entity_id,p_conference,p_entity,coalesce(p_payload->>'name',''),(p_payload->>'enabled')::boolean,p_payload->>'calculationMethod',nullif(p_payload->>'target',''),nullif(p_payload->>'operation',''),nullif(p_payload->>'quantity','')::numeric,nullif(p_payload->>'unitPrice','')::numeric,nullif(p_payload->>'amount','')::numeric,coalesce(p_payload->>'notes',''),1,actor,actor) on conflict(id) do update set name=excluded.name,enabled=excluded.enabled,calculation_method=excluded.calculation_method,target=excluded.target,operation=excluded.operation,quantity=excluded.quantity,unit_price=excluded.unit_price,amount=excluded.amount,notes=excluded.notes,revision=public.conference_finance_items.revision+1,updated_at=statement_timestamp(),updated_by=actor where public.conference_finance_items.conference_id=p_conference;
 end if;
 result:=platform_private.conference_finance_projection(p_conference);insert into public.conference_participation_operations(actor_user_id,operation_id,operation,request,result,created_at) values(actor,p_operation_id,'finance_mutation',req,result,statement_timestamp());insert into platform.audit_events(actor_user_id,actor_device_authorization_id,domain,module,action,entity_type,entity_id,scope_type,old_values,new_values,metadata,operation_id,source) values(actor,authz,'platform','conference','conference.finance.changed','conference_finance',coalesce(p_entity_id,p_conference),'platform',null,p_payload,jsonb_build_object('conferenceId',p_conference,'entity',p_entity,'permissionKey','conference.accounts.manage'),p_operation_id,'rpc');return result;
end $$;
revoke all on function platform_private.require_conference_finance_context(uuid,uuid,text,boolean),platform_private.conference_finance_projection(uuid),public.get_conference_finance(uuid,uuid),public.mutate_conference_finance(uuid,uuid,uuid,text,text,uuid,bigint,jsonb) from public,anon,authenticated,service_role;
do $$ declare sig regprocedure:='platform_private.route_canonical_conference_operation(uuid,uuid,bytea,uuid,text,jsonb)'::regprocedure;d text;marker text:='if p_operation=''get_conference_air_conditioning'' then';branch text:='if p_operation=''get_conference_finance'' then perform platform_private.require_exact_jsonb_keys(p_args,array[''p_conference_id'']);return public.get_conference_finance(p_actor_device_id,(p_args->>''p_conference_id'')::uuid);elsif p_operation=''mutate_conference_finance'' then perform platform_private.require_exact_jsonb_keys(p_args,array[''p_operation_id'',''p_conference_id'',''p_entity'',''p_action'',''p_entity_id'',''p_expected_revision'',''p_payload'']);return public.mutate_conference_finance(p_actor_device_id,(p_args->>''p_operation_id'')::uuid,(p_args->>''p_conference_id'')::uuid,p_args->>''p_entity'',p_args->>''p_action'',nullif(p_args->>''p_entity_id'','''')::uuid,(p_args->>''p_expected_revision'')::bigint,p_args->''p_payload'');elsif p_operation=''get_conference_air_conditioning'' then';begin d:=pg_get_functiondef(sig);if position(marker in d)=0 then raise exception 'P6I_B4C_ROUTER_PRECONDITION_FAILED' using errcode='55000';end if;execute replace(d,marker,branch);end $$;
commit;
